### ISSUE TITLE
Support round-robin discovery.

### ISSUE THREAD

**Issue by wrouesnel** [hvac/hvac#102]
When specifying a vault URL, it should be possible to request round-robin discovery if the first returned vault is still sealed.

i.e.

`http://vault.example.org` might resolve to several addresses `10.11.11.2,10.11.11.4,10.11.11.5,10.11.11.6,10.11.11.7`.

Currently if the client gets handed 1 address by DNS and it happens to be sealed, an exception is thrown. It would be convenient if the client would reliably try the other resolved addresses before failing to see if an unsealed node is available.

**Comment by otakup0pe** [comment]
Would welcome a PR for this ✨

**Comment by agrrh** [comment]
RR handling seems to be implemented in `urllib3` which is used by `requests` which `hvac` uses:
https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/connection.py#L28-L81

But using RR here causes really strange behavior:

```
$ host vault.example.com
vault.example.com has address 10.0.0.1
vault.example.com has address 10.0.0.2
vault.example.com has address 10.0.0.3
```

All addresses are reachable and leading to unsealed Vault nodes, but in 2/3 cases:
- First request is hang for very long time (longer than 5-7 minutes), so it was interrupted with Ctrl+C
- All following requests are going well

In 1/3 cases:
- First and following requests are going well

Same behavior when you try to perform request fagainst one of 2 standby servers, first request hang, then it's all okay.

So my assumption is that code is capable of getting active node address but unable to apply redirect properly: https://www.vaultproject.io/docs/concepts/ha.html#client-redirection

Here's the trace of failed request:

```
>>> client.is_authenticated()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hvac/v1/__init__.py", line 599, in is_authenticated
    self.lookup_token()
  File "hvac/v1/__init__.py", line 504, in lookup_token
    return self._get(path, wrap_ttl=wrap_ttl).json()
  File "hvac/v1/__init__.py", line 1589, in _get
    return self.__request('get', url, **kwargs)
  File "hvac/v1/__init__.py", line 1633, in __request
    allow_redirects=False, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 270, in recv
    rd = util.wait_for_read(self.socket, self.socket.gettimeout())
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 26, in _wait_for_io_events
    selector.select(timeout) if key[1] & events]
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 438, in select
    maxevents=max_events)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 94, in _syscall_wrapper
    result = func(*args, **kwargs)
KeyboardInterrupt
```

Just to approve that RR is broken in hvac, not in my setup: vault cli tool handles this perfectly.

**Comment by jeffwecan** [comment]
Thanks for that additional detail @agrrh! I believe I understand the issue a bit better now. While I think its totally worthwhile for someone to submit a patch to address things in this module, I'm curious when this sort of set up would actually be used in the real world. Isn't this sort of behavior covered by what is described at https://www.vaultproject.io/docs/concepts/ha.html#client-redirection? I.e., why not just configure the vault node's themselves to redirect traffic to the active node?

I suppose the idea is this route allows you to skip any sort of load balancer in front of the Vault nodes while still being able to use hvac should one of those nodes becomes seal (and thus unable to redirect)?

**Comment by agrrh** [comment]
Thank you, @jeffwecan !

I tried to sort the things out and end up proposing PR, but issue seems to be a little complex for me and right now I'm low on time to invest in it. Sad.

At least we could discuss issue further. There are 2 main ideas in which I'm unsure:

1. 

Yes, as you stated, nodes should redirect requests from standby to active and I believe they already do:
- we set up nodes, so they advertise themselves as `vault[1-3].example.org`
- we send request to common address like `vault.example.org`
- request reach one of the nodes via DNS RR
- (if it happen to reach standby-node, node redirects it further to active one)
- active node provides a response
Default `vault` CLI tool works fine with this kind of setup, so it seems that setup itself is proper enough.

Appreciate any details/updates/objections.

2.

To provide you some info about sanity of this setup:

We use RR to be able to apply same configuration to all the clients:
- It's complicated to update each client `VAULT_ADDR` whenever new leader is elected
- It's seems too  to update single DNS entry to point to active node

So RR record let us end up setting same common `VAULT_ADDR` and don't care about possible leader change or node fault. Could you probably propose other way to do so?

**Comment by jeffwecan** [comment]
Perfect, thanks for that context. I'll see if I can look at implementing changes to accomodating that sort of set up in hvac.

For what its worth, in my specific Vault deployment we have this sort of set up:

* Internally-facing Application Load Balancer (AWS) with three Vault nodes (HA cluster) in in its target group.
* The ALB is set to use /v1/sys/health as a "healthcheck" so the active Vault node in the cluster is the only target in-service.
* A CNAME record on a private DNS zone points to the ALB.
* Vault itself is configured with api_addr pointed to the ALB DNS record so that requests sent directly to inactive nodes get proxied over to the active node.

From there, we just set `VAULT_ADDR` to the DNS record for the ALB and things get routed to the right node just fine. Though its worth noting that the setup described is actively not recommended as things can get funky if the ALB health checks aren't configured correctly / don't work as expected. See: https://www.vaultproject.io/docs/concepts/ha.html#behind-load-balancers. The documentation at that link in particular also has a good run down generally of the various ways to navigate this sort of need.

**Comment by agrrh** [comment]
@jeffwecan 
ALB, that's it! Can't say how deep I appreciate your help, Jeff.

I guess, at this point it's safe to say that I was using Vault HA mode in a wrong way and such setup should be avoided. As documentation says, too.

**Comment by jeffwecan** [comment]
Closing this out until/unless anyone feels hvac needs to be updated to handle this issue as described.

**Comment by faizansiddiqu007** [comment]
ALB, that's it! Can't say how deep I appreciate your help, Jeff.

I guess, at this point it's safe to say that I was using Vault HA mode in a wrong way and such setup should be avoided. As documentation says, too

**Comment by colin-pm** [comment]
Is anyone interested in this feature being supported? I would say that I'm in favor of direction being handled by the backhand and not by this library.

If someone would like to pick up this feature, I'll leave the task open. Otherwise I'd like to close it in order to clean up the list of open issues.

**Comment by kaypeter87** [comment]
@briantist I think this can be closed as well. It is agreed that this library shouldn't support round robin and should be handled on the infra side with a properly set up Vault HA cluster.

**Comment by briantist** [comment]
I agree, the original closing seems to make sense, as the poster agreed there was a misconfiguration. I don't see any context on why it was re-opened shortly thereafter. I will close this out for now, but comments will not be disabled. If anyone wants to discuss an outstanding need for this, please let is know!
