### ISSUE TITLE
Missing endpoint for "sys/policies/"

### ISSUE THREAD

**Issue by catrielg** [hvac/hvac#1025]
Hi,

Currently the policy backend works with the /sys/policy/ endpoint: https://github.com/hvac/hvac/blob/main/hvac/api/system_backend/policy.py
(hvac docs: https://hvac.readthedocs.io/en/stable/usage/system_backend/policy.html)

According the Hashicorp Vault documentation there exists another backend to manage policies (/sys/policies) and this is where my ACLs are stored. https://developer.hashicorp.com/vault/api-docs/system/policies.

Please either support adding a path parameter to the existing backend so that we can specify different endpoint or create a new backend just for this endpoint.

Thank you!

**Comment by briantist** [comment]
Hi @catrielg , welcome and thanks for raising this! 

The docs are a little unclear (to me) since the `/sys/policy/` path seems to be (exclusively) for ACL policies, while the `/sys/policies/` path seems like it can be used for ACL, RGP, and EGP policies (with the latter two being enterprise features).

I'm not able to tell from the docs or find in my web searches what difference if any there is between ACL policies created at the different endpoints. Do you have any info on that?

Does the `/sys/policy/` set of endpoints not show ACLs policies created via `/sys/policies/acl/`?

**Comment by catrielg** [comment]
Hi @briantist, thanks for replying. 

I am not sure about whether `/sys/policy/` will show anything and sadly I do not have a way to check. The permissions I have are strictly limited to `/sys/policies/`,  I can also see that our admins do not have `/sys/policy/` anywhere on their policies. This leads me to believe this endpoint is not used on the Namespace I am working on. 

On top of that when inspecting the HTTP requests while using the WebUI I can see that when I view a policy I go to the `/v1/sys/policies/` endpoint. 

For now I am just using the HTTP API to work around this issue, however it would be cool to have it supported in hvac.

**Comment by briantist** [comment]
I see, ok. It sounds like this is somewhat similar to https://github.com/hvac/hvac/issues/1017 in that Vault may provide different paths to do the same thing, but since policies are simple path-based matching systems and don't know anything about the underlying endpoints, as a library we need to support the different ways to access that functionality, because people have different policy schemes in place.

I don't know when I might personally be able to look into this further or implement it, but I'd be happy to discuss implementation options and review a PR if you or anyone reading is interested!

**Comment by catrielg** [comment]
@briantist I'd be happy to help draft some kind of PR, I'm relatively new to development and contributing to open source projects but would love to learn a thing or two.

**Comment by briantist** [comment]
@catrielg that would be great! We're definitely looking for more contributors: https://github.com/hvac/hvac/discussions/994

You could get started by having a look at the contributing doc: https://github.com/hvac/hvac/blob/main/CONTRIBUTING.md

That doc needs work; it's probably geared a little more toward more experienced developers, but if you get stuck somewhere (even at the beginning) please let me know and we'll work through it, and hopefully improve the docs in the process.

Improving the developer experience is important for a project and it's definitely an area I want to work on.

---

For this change in the particular, right now the "hardest" part is deciding _how_ to implement it. Do we add a `path` parameter, or look to create new methods in the library, or add a selection parameter, etc....? So your input (and that of others reading) will be important there.

Initially I am thinking of it like this:

### `path` parameter
This would make `path` a parameter on these methods, which could have a default of the current path, but allow the caller to override it by passing in an arbitrary value.

Pros:
- simple to implement
- allows for easier code in agnostic applications
- possibly allows for setting non-ACL policy types, which are only available in the `policies` path (this is also kind of a con in my opinion)

Cons:
- freeform text in the path means you could put any path there, which kind of makes into a generic set of methods that aren't really about policies unless you use the defaults or supply exactly the right path
- above complicates testing
- also related to above, other than the default value, not immediately clear which path should be used if you want the alternative path, unless you read the documentation
- muddles together what are two different sets of API calls into a single method

### selection parameter
This would add a new parameter that would allow you to select from the two different sets of paths that can be used for ACL policies. The parameter could be a boolean if the number of possibilities remains at two, for example `use_policies_path` or `use_alternate_path`. Or it could be a string/enum where you choose from a list of options, like `path_set` which could be set to `policy` or `policies`.

Pros:
- does not allow for arbitrary paths
- does not require knowing the actual paths involved
- allows for easier code in agnostic applications
- easy to implement

Cons:
- a little more complication for testing
- does not allow for the possibility of using these endpoints on non-ACL policies (kind of a pro imo)
- parameter feels kind of awkward to me; if your use case needs this you need to add it to every call unless we also provide a way to set it once centrally, something we don't really do now for other things
- if the list of possible paths expands (hopefully it won't), it requires a library update to support it
- muddles together what are two different sets of API calls into a single method

### new methods / class
This would involve leaving the current policy endpoints alone, and creating most likely a new class `Policies` alongside the existing `Policy` class, to contain the methods needed. In this way you would make different calls for the different methods.

Pros:
- more clearly defined set of endpoints that correspond to the different HTTP APIs
- changes in Vault to each set of APIs can be implemented in the corresponding classes in a more straightforward way
- if one set of calls is deprecated or removed in Vault, we can more easily mark/remove them in the library without affecting the other
- testing is more straightforward
- could implement non-ACL policies later as their own extension points

Cons:
- more code to write (and test)
- agnostic applications likely need a conditional somewhere, or wrapping, to choose the right endpoint

---

The only other thing I'll point out is that a workaround is possible if you prefer overriding the path: the generic [`Client.write` ](https://hvac.readthedocs.io/en/stable/source/hvac_v1.html#hvac.v1.Client.write) and [`Client.read`](https://hvac.readthedocs.io/en/stable/source/hvac_v1.html#hvac.v1.Client.read) methods can write and read against arbitrary paths.

In my opinion, these are preferable to adding arbitrary path support to specific endpoints.

---

Let me know what you think!
