### ISSUE TITLE
Add support for "associated_data" parameter in transit.encrypt_data and transit.decrypt_data.

### ISSUE THREAD

**Issue by juergw** [hvac/hvac#1107]
Vault supports now an "associated_data" parameter, see:
https://developer.hashicorp.com/vault/api-docs/secret/transit#encrypt-data
https://developer.hashicorp.com/vault/api-docs/secret/transit#decrypt-data

But hvac does not yet support this:
https://hvac.readthedocs.io/en/stable/usage/secrets_engines/transit.html#decrypt-data
https://hvac.readthedocs.io/en/stable/usage/secrets_engines/transit.html#encrypt-data

Please add support for this parameter.

**Comment by JordanStopford** [comment]
Hi @briantist I popped in a simple fix for this a while back - any chance of getting this merged?
