### ISSUE TITLE
Client Certificate CA

### ISSUE THREAD

**Issue by stongo** [hvac/hvac#111]
Is there a way to specify a CA certificate when initializing client to go along with Certificate and Private Key in the `cert` tuple? The Absence of a way to specify CA file is a deal breaker for this library unfortunately.

**Comment by ericksepulveda** [comment]
I think I'm having an issue related to this:

```bash
2017-01-30 16:59:37.543964 I | http: TLS handshake error from <host>: remote error: tls: unknown certificate authority
```

**Comment by ganlaksh** [comment]
i am hitting the same problem.... using the verify=False option to workaround this.

**Comment by bitprophet** [comment]
Fun note: the `verify` kwarg in the constructor and/or other methods, is passed through directly to an internal `requests.Session`, whose `verify` argument can _also_ take a string value which is the path to one's CA cert. Seems to work fine for me!

**Comment by cscetbon** [comment]
It should at least be added to the documentation

**Comment by otakup0pe** [comment]
I struggled with this a bit recently... Can add something to the README.

**Comment by FabianFrank** [comment]
Passing a string that contains the path to a CA bundle, as described in the request docs works. You'll get a warning in some IDEs though, because the type hint in hvac is bool and not Union[str, bool] or just no type hint. I've addressed that in my PR.

**Comment by jeffwecan** [comment]
Between #230 and #238 I am going to consider this issue closed. Please open up a new issue if you feel like additional work is needed.
