### ISSUE TITLE
Update client.kv.default_kv_version in doc 

### ISSUE THREAD

**Issue by benzch** [hvac/hvac#1113]
In the following file: https://github.com/hvac/hvac/blob/main/docs/usage/secrets_engines/kv.rst
The docs should be updated from: 
```
import hvac
client = hvac.Client()

client.kv.default_kv_version = 1
client.kv.read_secret(path='hvac')  # => calls hvac.api.secrets_engines.KvV1.read_secret
```

to:

```
import hvac
client = hvac.Client()

client.secrets.kv.default_kv_version = 1
client.kv.read_secret(path='hvac')  # => calls hvac.api.secrets_engines.KvV1.read_secret
```

When running with latest version of havc and client.kv.default_kv_version getting the following error: 
```
│ Program: /usr/local/bin/python3
│ Error Message: Traceback (most recent call last):
│   File "/Users/xxxx/Desktop/yyyy/zzzz/../vvvv/shared-modules/vault_record/read_secret.py", line 85, in <module>
│     main()
│   File "/Users/xxxx/Desktop/yyyy/zzzz/../vvvv/shared-modules/vault_record/read_secret.py", line 63, in main
│     client.kv.default_kv_version = get_mount_version(client, mount_point)
│   File "/usr/local/lib/python3.10/site-packages/hvac/v1/__init__.py", line 155, in __getattr__
│     return utils.getattr_with_deprecated_properties(
│   File "/usr/local/lib/python3.10/site-packages/hvac/utils.py", line 252, in getattr_with_deprecated_properties
│     raise AttributeError(
│ AttributeError: 'Client' has no attribute 'kv'
│
│ State: exit status 1
```

I am missing something  or the docs are not updated?

**Comment by rgl** [comment]
I think this is blocked by https://github.com/hvac/hvac/issues/1061

**Comment by briantist** [comment]
Hi @rgl , thanks for finding this! 
It should not be blocked by #1061 since the other tags in RTD still work, namely, `main` will still show you what `latest` is supposed to show, and the `stable` tag is also correct.

Would it be too much trouble for you to put up a PR with the changes?

**Comment by briantist** [comment]
I found where the original property was removed, it was quite a while ago!
https://github.com/hvac/hvac/pull/311/files#diff-c14f37a0d0f4f67dc145b13ddba81fe57b72293de4f5d39b443b97a96736dad1L131-L137
