### ISSUE TITLE
Add coverage for automatic snapshot route

### ISSUE THREAD

**Issue by tot19** [hvac/hvac#1150]
If ok, will open a PR for the enterprise automatic snapshots feature. API doc is [here](https://developer.hashicorp.com/vault/api-docs/system/storage/raftautosnapshots). Will add CRUD + list operations to hvac/api/system_backend/raft.py.

**Comment by briantist** [comment]
Sounds great, please do!
I think we will not be able to run integration tests in CI due to #850 but please write tests anyway if possible so that they can be flipped on if we fix that. Also unit tests should be possible either way.

**Comment by tot19** [comment]
Apologies took me a bit to get to this - have been swamped lately.

Just opened the PR .. Only thing I would add to the PR notes is that the ent versions 1.7 and 1.8 do technically support these endpoints; however, they appear to not be using raft storage in the test config.

https://github.com/tot19/hvac/actions/runs/8966262561/job/24621406473
