### ISSUE TITLE
MacOS: A Worker Was Found in a Dead State - Reopen

### ISSUE THREAD

**Issue by rgadwagner** [hvac/hvac#1192]
Ansible 2:17 on Python 3.12, in a freshly installed venv using PyEnv with HVAC - latest.
Apple M2 Pro: Sonoma 14.6.1

https://github.com/hvac/hvac/issues/817

Appears to be happening again, but at this point on my machine the export from the issue above does not fix my issue.  It's worked in the past on my mac but does not appear to be functional now.

VENV Installation:
```
$ pyenv install 3.12
$ pyenv virtualenv 3.12.6 ansible312
$ pyenv activate ansible312
$ pip install ansible
$ pip install ansible-lint pywinrm hvac
$ pip install pyOpenSSL cryptography idna requests setuptools six
$ pip install requests-kerberos pykerberos
$ ansible-galaxy collection install servicenow.servicenow vmware.vmware_rest:2.1.5
```

```
╰─ env | grep VAULT                                                                                                                                            ─╯
VAULT_ADDR=https://correct.server.host
VAULT_TOKEN=<my renewed token here>

╰─ env | grep OBJ                                                                                                                                              ─╯
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

╰─ ansible-playbook -i inventory decommission_server_phase1.yml -e host_fqdn="host.dom.ext"

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Build Cleanup | Clean failed builds] ***********************************************************************************************************************

TASK [Build Cleanup | Obtain required credentials from vault] ****************************************************************************************************
ERROR! A worker was found in a dead state

╰─ ansible --version                                                                                                                                           ─╯
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/Users/dwagner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dwagner/.pyenv/versions/3.12.6/envs/ansible312/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/dwagner/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/dwagner/.pyenv/versions/ansible312/bin/ansible
  python version = 3.12.6 (main, Oct  3 2024, 12:43:16) [Clang 16.0.0 (clang-1600.0.26.3)] (/Users/dwagner/.pyenv/versions/3.12.6/envs/ansible312/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

The environment was working fine up to the point I added the most recent version of hvac at which point it's now broken for anything using that library.

```
- name: Build Cleanup | Clean failed builds
  hosts: localhost
  gather_facts: false

  vars:
    sbase: "kv/data/"

  tasks:
    - name: Build Cleanup | Obtain required credentials from vault
      set_fact:
        user: "{{ lookup('hashi_vault', 'secret=' + sbase + 'decom:username') }}"
```

As I don't see hundreds of posts or open threads on this I'm assuming this is still working for some subset of people / majority.  I just don't know how.  Any help would be most appreciated.

**Comment by rgadwagner** [comment]
Apparently a co-worker of mine found another export to go along with the OBJC setting:

export no_proxy="*"

WIth both of these set, MacOS is functional with hvac.  I'm not sure how this contributes but it has me functional at this point.

```
export no_proxy="*"
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

**Comment by briantist** [comment]
@rgadwagner these are known issues with ansible that are specific to macos. There are a number of factors that can trigger it or  not, so a different version of `hvac` may trigger it but is also not the actual cause. This goes back years and doesn't only affect hvac and community.hashi_vault, but there's nothing we can do about it in this library unfortunately:
- https://github.com/ansible/ansible/issues/49207

**Comment by prometheanfire** [comment]
@rgadwagner thank you for the documentation of the workaround, the `no_proxy="*"` thing is new to me.  If you don't mind me asking, is that documented anywhere?

**Comment by rgadwagner** [comment]
I have no idea.  The co-worker that found this did find it somewhere so i'm guessing it's out there, but as to being documented for this error?  I don't think so, that's why I was stumped.  

The only thing i've ever seen "documented" as a workaround to this issue was the "Export" OBJC command above, but that stopped working for me for a recent version of hvac.  The above is what made things work for me, and honestly, I was just as interested in publicly documenting this in a searchable form than I was getting things updated.

**Comment by Markethh** [comment]
I'm having this issue again since upgrading to macOS 26 (Tahoe). Previously the `export no_proxy='*'` workaround solved it for me, but I'm now a little stumped if the most recommended workaround no longer works.

I've tried a combination of both `no_proxy='*'` and `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` with no luck (also tried one but not the other).
