### ISSUE TITLE
Add support for VAULT_TLS_SERVER_NAME

### ISSUE THREAD

**Issue by sudo-bmitch** [hvac/hvac#121]
In my environment I need to connect to vault using an IP address (specifying which vault server in a potential set of containers with identical certificates). However my certificate is only valid for the hostname since the IP addresses are not predictable (vault is running as a docker container). I'm able to do this with the VAULT_TLS_SERVER_NAME environment variable when using the vault cli client [documented here](https://www.vaultproject.io/docs/commands/environment.html). Is there a way to add support for this, or if not, can certificate verification be disabled?

**Comment by TerryHowe** [comment]
hvac.Client(url=url, verify=False)

What I've done under somewhat similar circumstances is put haproxy in front with rules to route to the active and if your haproxy is doing tls...

**Comment by bmitch3020** [comment]
The `verify=False` works for disabling the check, through it throws a mess of errors. I've found [request_toolbelt](https://toolbelt.readthedocs.io/en/latest/adapters.html#hostheaderssladapter) which would resolve the situation for me if we can pass custom headers in the request. E.g. I can do the first 3 lines of the below:

```
import requests
from requests_toolbelt.adapters import host_header_ssl
s = requests.Session()
s.mount('https://', host_header_ssl.HostHeaderSSLAdapter())
s.get("https://93.184.216.34", headers={"Host": "example.org"})
```

But I need a way to add a headers entry for "Host".

**Comment by TerryHowe** [comment]
You could probably pass in your own requests session?  Would that help? 

 https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L22

**Comment by bmitch3020** [comment]
The session only gets me halfway there, the get/post call is inside the hvac library and I need to add a header to that call.

**Comment by otakup0pe** [comment]
While passing in a custom sessions is possible, this would be cool to have. Would love to see a PR.

**Comment by ermik** [comment]
It's highly painful to use this package when Vault is registered in a service discovery solution (e.g. Consul) — there are no URLs in that environment

**Comment by jeffwecan** [comment]
If any folks need greater control over how hvac leverage requests, the [Adapter](https://github.com/hvac/hvac/blob/master/hvac/adapters.py) Client attribute is now available: https://hvac.readthedocs.io/en/latest/advanced_usage.html#custom-requests-http-adapter

Given that, I'm closing out this issue. Though if anyone would like to see a variation on the Adapter class as outlined in this issue included in hvac itself, a PR is totally welcome.
