### ISSUE TITLE
Input validation might be good

### ISSUE THREAD

**Issue by ericfode** [hvac/hvac#129]
It looks like most of these functions do nothing to keep you from passing invalid parameters to vault. It might be good if we did more.

**Comment by otakup0pe** [comment]
It seems to me like addressing the root of #133 would help a _ton_ with input validation. If I'm not missing something, I'll close this one out in favor of 133.

**Comment by jeffwecan** [comment]
This is something well keep in mind going forward, but without any recent input on the matter I figure we can close out the issue for now.
