### ISSUE TITLE
Add Support For kv Version 2 Secret Engine

### ISSUE THREAD

**Issue by wknapik** [hvac/hvac#183]
Failing example from the README:
```
>>> import os, hvac
>>> client = hvac.Client(url='http://localhost:8200', token='foobar')
>>> client.is_authenticated()
True                                                                                                                                           
>>> client.write('secret/foo', baz='bar', lease='1h')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/hvac/v1/__init__.py", line 64, in write
    response = self._put('/v1/{0}'.format(path), json=kwargs, wrap_ttl=wrap_ttl)
  File "/usr/lib/python3.6/site-packages/hvac/v1/__init__.py", line 1242, in _put
    return self.__request('put', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/hvac/v1/__init__.py", line 1278, in __request
    self.__raise_error(response.status_code, text, errors=errors)
  File "/usr/lib/python3.6/site-packages/hvac/v1/__init__.py", line 1290, in __raise_error
    raise exceptions.InvalidPath(message, errors=errors)
hvac.exceptions.InvalidPath: {"request_id":"494d7306-ede4-bc4f-47d5-747bff182df3","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put' for this operation."],"auth":null}
>>> print(client.read('secret/foo'))
None
>>>
```
For reference, here's the cli - correct call (`vault kv put`/`vault kv get`) and incorrect call (`vault write`; produces the same error):
```
% vault kv put secret/bar baz=qux  
Key              Value
---              -----
created_time     2018-05-22T11:08:01.003383998Z
deletion_time    n/a
destroyed        false
version          1
% vault kv get secret/bar
====== Metadata ======
Key              Value
---              -----
created_time     2018-05-22T11:08:01.003383998Z
deletion_time    n/a
destroyed        false
version          1

=== Data ===
Key    Value
---    -----
baz    qux
% vault write secret/baz qux=quux 
Error writing data to secret/baz: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/secret/baz
Code: 404. Errors:


WARNING! The following warnings were returned from Vault:

  * Invalid path for a versioned K/V secrets engine. See the API docs for the
  appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put'
  for this operation.
%
```

Tested on Linux, using hvac 0.5.0 and python 2.7.15 and 3.6.5.

**Comment by wknapik** [comment]
Hi @jeffwecan. I honestly don't know (I'm not even using Vault anymore), but you can just run the test above against the patched hvac to find out. Just run `vault server -dev` to start the server, call `python` to get an interactive console and paste the 5 lines from the example. If it works, it's likely the solution. The best place to confirm that this is correct is the Vault API documentation.

**Comment by AmundsenJunior** [comment]
@jeffwecan @wknapik I think I found the discrepancy. In 0.10.x, Vault is now expecting GET and PUT/POST API requests to be directed at "secret/data/foo", not "secret/foo" (even though the CLI would take "kv get/put" commands against "secret/foo"). Also, data should be passed to the "data" key, so the **kwargs acceptance of multiple key-value pairs in a client.write() call no longer work. 

Here's a working example in a Python 3 console with Hvac 0.5.0 and Vault 0.10.2:
```python
>>> import hvac, os
>>> client = hvac.Client(url=os.environ['VAULT_ADDR'], token=os.environ['VAULT_TOKEN'])
>>> data = {
...   "user": "name",
...   "pass": "word"
... }
>>> client.write('secret/data/redis', data=data)
{'warnings': None, 'wrap_info': None, 'renewable': False, 'auth': None, 'data': {'created_time': '2018-06-14T23:16:32.72739499Z', 'destroyed': False, 'deletion_time': '', 'version': 1}, 'lease_duration': 0, 'request_id': 'fc082499-82f4-79bb-640b-22c43acfcc3c', 'lease_id': ''}
>>> print(client.read('secret/data/redis'))
{'renewable': False, 'data': {'data': {'user': 'name', 'pass': 'word'}, 'metadata': {'destroyed': False, 'deletion_time': '', 'created_time': '2018-06-15T01:31:14.398781526Z', 'version': 1}}, 'request_id': '7f09881f-534e-9e92-cf3a-a0739c8f2dc8', 'lease_duration': 0, 'auth': None, 'wrap_info': None, 'lease_id': '', 'warnings': None}
```

It'd be desirable to either update documentation accordingly and/or update the Client.write function to aggregate the key-value args into a data dict to then be passed to the request function.

Reference that was linked on #182 for v2 HTTP API: https://www.vaultproject.io/api/secret/kv/kv-v2.html#create-update-secret

**Comment by AmundsenJunior** [comment]
Not sure if this should be filed separately as a new issue, but the same API breakage appears to hold true for listing secrets.

`GET /v1/secret/path?list=true` no longer works, which is how hvac implements list calls.

In the new HTTP API, listing secrets is now only through: `LIST /v1/metadata/secret/path`.

V1 HTTP API reference: https://www.vaultproject.io/api/index.html#reading-writing-and-listing-secrets
V2 HTTP API reference: https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets

**Comment by jeffwecan** [comment]
Yeah that makes enough sense, thanks for the additional context @AmundsenJunior! I figure we can use this issue as a general purpose "make sure hvac works with the v2 kv secret backend while still maintaining support for v1 kv" issue.

**Comment by Jukape** [comment]
The above pull requests adds v2 functionality for read, write, delete and listing of secrets.

The version of the back end is auto detected using the list secrets backend and checking the version of the kv, if this is not found the version defaults back to 1.

Note: As mentioned above, in v1 to access a secret all paths were prepended with secret/YOUR_PATH, so a list would of been:

get /v1/secret/path?list=true

in v2 the paths have changed to secret/SUBPATH/YOURPATH, so a v2 list is:

get /v1/secret/metadata/path?list=true

This means that if you are accessing the secrets programmatically, all of the secrets paths would be incorrect, to remove the need to go through and update all of the code that access secrets programmatically, if the backend is v2 and the path passed in begins with 'secrets/' this is removed

**Comment by Tan4eto** [comment]
I have also stumbled upon this behaviour at my workplace and I've used a workaround. I hope there is progress on the matter. Could we expect a feedback soon? Thanks very much!

**Comment by jeffwecan** [comment]
Howdy @Tan4eto! I'm hoping to have solid support for kv v1 *and/or* kv v2 in the next release of hvac. That release version will be 0.6.4 and I expect that version to be released first thing next month (September 1st).

**Comment by jeffwecan** [comment]
FYI, I'm going to go ahead and repurpose this issue as a generic "Key/Value version 2 secrets engine support" issue and direct some related issues here to keep things centralized.

**Comment by jeffwecan** [comment]
@AmundsenJunior / @Tan4eto / @cityofships / @Jukape: I've attempted to cover support for KV v2 paths by adding in a couple new kv secret engine-specific classes. If any of y'all have any interest in providing it, I would love to get some feedback on those changes. You can check out the general usage for the new classes here: https://hvac.readthedocs.io/en/latest/usage/secrets_engines/kv.html

As an aside, I *did not* attempt to add any sort of auto-detection of KV versions as of yet though I do like the idea generally. When exploring that option, I wasn't able to work out a way to do that sort of detection in a manner that would do the trick without adding a bit more complexity than I was comfortable with.

I'm going to close this issue out since its (ideally) been addressed. However if anyone does have comments, feel free to leave them here and/or create a new issue.

**Comment by vaddisrinivas** [comment]
API  is not working for vault version 0.11.4, for kv version 2. any help on that?

**Comment by jeffwecan** [comment]
@vaddisrinivas: I haven't heard of any similar reports of compatibility issues with that version of Vault thus far. Could you please create a new issue with details on the specific issue(s) you're encountering?

**Comment by janmasarik** [comment]
I was checking out possibilities of auto-detection and came up with simple hack for backwards compatibility. Please let me know what you think about it as I think it may be useful for people migrating from KV 1 to KV 2 on runtime.

1. Call `/secret/config` API endpoint on init of the client to dynamically determine if it's KV 1 or KV 2. It should return either error/invalid response for **KV1** and response containing `{"data": {"max_versions":0, ...}}` for **KV2** https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-kv-engine-configuration
2. Make simple `read_secret` / `list_secrets` / ... wrappers for KV2 reading the most recent version of the secret. 
3. Make it configurable in `client.kv` through some parameter , eg. `auto_kv_version_detect=False` with warning about this magical behaviour. 😅 

What do you think @jeffwecan? Is this that *bit more complexity* you were talking about?

**Comment by jeffwecan** [comment]
Yup, that sounds like a viable sort of solution. I'm going to go ahead and spin off this discussion to a new issue though so it has the appropriate visibility...

**Comment by maxadamo** [comment]
Do these two links shed some light? (mentioning the ruby library too, since it is an official library maintained by hashicorp). 
https://www.vaultproject.io/api/system/mounts.html#options
https://github.com/hashicorp/vault-ruby/pull/196/commits/5f8fb8c2193fcf6befe6b52ad9488c795234baa1

**Comment by jeffwecan** [comment]
@maxadamo: Yes, that is good context to bring in, thanks! Two things on that point generally:

* Moving forward, I'd like to segment any ongoing discussion around this matter to https://github.com/hvac/hvac/issues/383 as that issue is still open while the general concern in this issue has been closed out.
* From what I've seen, KV v2 is only the "default" for Vault when run in dev mode (i.e., `vault server -dev`), which is something I personally didn't realize initially:
  > Additionally, when running a dev-mode server, the v2 kv secrets engine is enabled by default at the path secret/ (for non-dev servers, it is currently v1). It can be disabled, moved, or enabled multiple times at different paths. Each instance of the KV secrets engine is isolated and unique.

  reference: https://www.vaultproject.io/docs/secrets/kv/kv-v2.html
