### ISSUE TITLE
how to list auth/token/accessors

### ISSUE THREAD

**Issue by hmlingesh** [hvac/hvac#184]
Hello Team,

does this client support to list all accessors for the vault, I mean for below request how I can use from this client.

curl --silent  --header "X-Vault-Token: XXXXXXXX"  --request LIST  http://127.0.0.1:8200/v1/auth/token/accessors)

Regards
Lingesh M

**Comment by ChingTsai** [comment]
`client.list("auth/token/accessors")` works for me

**Comment by jeffwecan** [comment]
FWIW, more explicit support for the token auth method in hvac is forthcoming at some point. At that time, you can expect something along the lines of `hvac.Client().token.list_accessors()` to be available. In the interim, @ChingTsai's example would be a valid option from what I can see (though would need modifications if the relevant token auth method was mounted under a different path/mount point). Given this, I'm going to close this issue out for the time being. Please feel free to reopen it if needed.
