### ISSUE TITLE
Document Examples of Access Key Retrieval for AWS IAM Auth Usage

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#204]
[Moving this discussion from https://github.com/ianunruh/hvac/pull/155#issuecomment-400119225 into an issue for visibility. cc: @RevolutionTech]

re: https://github.com/ianunruh/hvac/pull/170

Sorry if this is a stupid question, but since the API in https://github.com/ianunruh/hvac/pull/170 now requires an access key ID and a secret access key, is there any way we can use IAM auth without having those at runtime? For the application I work on, we store those credentials in Vault currently.

I realize that we can infer credentials with `boto3` using the following code:
```python
import boto3
session = boto3.Session()
credentials = session.get_credentials()
print(credentials.access_key, credentials.secret_key)
```
but boto3 [attempts to collect](https://boto3.readthedocs.io/en/latest/guide/configuration.html) the access key and secret key from many different locations (such as environment variables, and from `~/.aws/credentials`) before it ultimately uses the IAM role, so if we were to rely on this we may not collect the credentials that correspond to the IAM role we want.

Is there some other way to extract an access key and secret key from an IAM role that I'm missing?

**Comment by jeffwecan** [comment]
Hi @RevolutionTech, if the context is a EC2 instance's instance role, you can retrieve that information from the EC2 metadata service. E.g.:

```shell
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/<some ec2 role name>/ ; echo
{
  "Code" : "Success",
  "LastUpdated" : "2018-06-26T12:08:26Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "<access_key_id>",
  "SecretAccessKey" : "<secret_access_key>",
  "Token" : "<token>",
  "Expiration" : "2018-06-26T18:42:27Z"
}
```

If you're inquiring about a situation outside of an EC2 instance role, I'd love to hear about the specific details. I figure we can use this issue to track the various use cases folks have for the AWS IAM auth method and ultimately update our documentation to include examples of how to handle those cases. Thanks for brining the matter up!

**Comment by jeffwecan** [comment]
Here is a snippet of how to do the same sort of cURL using python's requests module instead:

```python
import logging

import requests
from requests.exceptions import RequestException

logger = logging.getLogger(__name__)

EC2_METADATA_URL_BASE = 'http://169.254.169.254'

def load_aws_ec2_role_iam_credentials(role_name, metadata_url_base=EC2_METADATA_URL_BASE):
    """
    Requests an ec2 instance's IAM security credentials from the EC2 metadata service.
    :param role_name: Name of the instance's role.
    :param metadata_url_base: IP address for the EC2 metadata service.
    :return: dict, unmarshalled JSON response of the instance's security credentials
    """
    metadata_pkcs7_url = '{base}/latest/meta-data/iam/security-credentials/{role}'.format(
        base=metadata_url_base,
        role=role_name,
    )
    logger.debug("load_aws_ec2_role_iam_credentials connecting to %s" % metadata_pkcs7_url)
    response = requests.get(url=metadata_pkcs7_url)
    response.raise_for_status()
    security_credentials = response.json()
    return security_credentials
```
```
>>> load_aws_ec2_role_iam_credentials('some ec2 role name').keys()
[u'Code', u'LastUpdated', u'AccessKeyId', u'SecretAccessKey', u'Token', u'Expiration', u'Type']
>>>
```

If that is generally the sort of process you're after, it might could also make sense to add that sort of helper method to hvac?

**Comment by RevolutionTech** [comment]
Thanks @jeffwecan, this is very helpful! It looks like I should be able to use logic like this to get the access key ID and secret access key on EC2 instances, which is useful for one of the applications we run.

However, we do have a few other applications using `hvac` that run on Lambdas. Unfortunately, it doesn't look like this process works on those. Is there anything you'd recommend in that case to get the access key ID and secret access key?

**Comment by jeffwecan** [comment]
I don't currently have any direct experience with the lambda side of things. However I have heard of that use case coming up with our own Vault deployment. So I'll investigate along those lines when I have some time and let you know what I turn up. :+1:

**Comment by jeffwecan** [comment]
@RevolutionTech: Actually, taking a look at the AWS docs, it looks like the lamba execution environment exposes those credentials as environmental variables which would make that type of AWS IAM auth integration relatively straightfoward: https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html#lambda-environment-variables. E.g., `os.getenv('AWS_ACCESS_KEY_ID')` & `os.getenv('AWS_SECRET_ACCESS_KEY')` . Let me know if that option fits the mold and we can see about updating the docs with some example usage for python apps running on lambda?

**Comment by jeffwecan** [comment]
Also worth noting on the previous point about EC2 instance-based AWS IAM auth: the AWS EC2 auth method is probably a better option generally in that case. To continue using this issue to document some examples, here is a method we use to grab the PCKS7 identity document when authenticating EC2 instances to Vault in that manner (you'll notice it is similar to the previous snippet I shared as I used it as the basis for the example `load_aws_ec2_role_iam_credentials()` method :P):

```python
import logging

import requests

logger = logging.getLogger(__name__)

EC2_METADATA_URL_BASE = 'http://169.254.169.254'


def load_aws_ec2_pkcs7_string(metadata_url_base=EC2_METADATA_URL_BASE):
    """
    Requests an ec2 instance's pkcs7-encoded identity document from the EC2 metadata service.
    :param metadata_url_base: IP address for the EC2 metadata service.
    :return: string, pkcs7-encoded identity document from the EC2 metadata service
    """
    metadata_pkcs7_url = '{base}/latest/dynamic/instance-identity/pkcs7'.format(base=metadata_url_base)
    logger.debug("load_aws_ec2_pkcs7_string connecting to %s" % metadata_pkcs7_url)

    response = requests.get(url=metadata_pkcs7_url)
    response.raise_for_status()
    
    pcks7 = response.text.replace('\n', '')

    return pcks7
```

**Comment by RevolutionTech** [comment]
The project I'm working on is actually a wrapper around `hvac` (that tightly integrates `hvac` into Django) and it's running on both EC2 and Lambda instances, so I think in my case I will need to support both which means I'll have to create a helper that's something like this:
```python
import os


def infer_credentials_from_iam_role(iam_role):
    on_lambda = 'AWS_LAMBDA_FUNCTION_NAME' in os.environ
    if on_lambda:
        return os.environ['AWS_ACCESS_KEY_ID'], os.environ['AWS_SECRET_ACCESS_KEY']
    else:
        security_credentials = load_aws_ec2_role_iam_credentials(iam_role)
        return security_credentials['AccessKeyId'], security_credentials['SecretAccessKey']
```

Do you think adding a helper similar to this into `hvac` could be helpful to others? With this, perhaps it would be possible to have a method similar to `auth_aws_iam` that accepts an IAM role without credentials.

**Comment by jeffwecan** [comment]
I personally would like to see hvac handle as much of that sort of logic as possible (without the behavior going to far and being unexpected). Going that route reduces the amount of extra code needed from callers just to leverage hvac in the first place. So, yes, I think either having a method to perform that sort of lookup and call `auth_aws_iam` or something similar would be valuable.

**Comment by jeffwecan** [comment]
I'm thinking I may hold off on including the documentation additions until we can get some proper docs published (E.g., http://readthedocs.io/)

**Comment by flyinbutrs** [comment]
If you're using boto already as part of your project, I recommend using the following python, since it will work with any method of default config retrieval (credentials file, env, assume role, IAM role on EC2/ECS/Lambda):

````python
import botocore
credentials = botocore.session.Session().get_credentials().__dict__
````

**Comment by RevolutionTech** [comment]
@flyinbutrs The problem with this approach is that you cannot prioritize which method you wish to use to retrieve credentials, so if you have access keys in the environment variables for example, but want to apply the credentials from the IAM role, there is no way to.

**Comment by RevolutionTech** [comment]
No worries. I still think your solution will solve most people's use cases. :+1:

**Comment by flyinbutrs** [comment]
You know what, I'm going to stop, I see the issue now, and have reading comprehension issues ;)
