### ISSUE TITLE
Client.unwrap missing client token error

### ISSUE THREAD

**Issue by matkam** [hvac/hvac#249]
The Client.unwrap function should not pass the cubbyhole token in the request body, as Vault now expects it in the header. The workaround is to set the cubbyhole token as the client token.

This produces an error:
```
vc = hvac.Client()
unwrapped = vc.unwrap(<cubbyhole_token>)
```

Workaround:
```
vc = hvac.Client()
vc.token = <cubbyhole_token>
unwrapped = vc.unwrap()
```

**Comment by jeffwecan** [comment]
Hi @matkam, thanks for the report! I believe the intention was to provide both options per the documentation at https://www.vaultproject.io/api/system/wrapping-unwrap.html:

> This endpoint can be used by using a wrapping token as the client token in the API call, in which case the token parameter is not required; or, a different token with permissions to access this endpoint can make the call and pass in the wrapping token in the token parameter. Do not use the wrapping token in both locations; this will cause the wrapping token to be revoked but the value to be unable to be looked up, as it will basically be a double-use of the token!

In other words:

* You can set the wrapped token as the "client" token and make the unwrap call if you are going that route
* Alternatively, if you already have a generic token set on the client and have a *seperate* token you wish to unwrap, that wrapped token can be passed as a parameter to this method. 

What changes to this behavior for hvac in particular would you expect to be made to resolve this issue?

**Comment by matkam** [comment]
Hi @jeffwecan, thanks for getting back to me!
I must have misunderstood what changed behind the scenes here since upgrading Vault to 0.4.10, along with Vault Gatekeeper (http://nemosupremo.github.io/vault-gatekeeper/). Reading through the documentation you linked again, it makes more sense why Client.unwrap() works the way it does.

I'm not sure what changes in hvac would best mitigate the confusion. Maybe there could be an additional "client_token" parameter. And/or, if the hvac Client object has an empty token value, use the wrapping token as the Client token.

I'll close this issue as the current behavior seems to be intended.

**Comment by jeffwecan** [comment]
Got ya, and those are totally valid points about the changes to the parameter naming and/or behavior. I'm hoping to eventually refactor all the system backend methods into individual class(es) at some point so I'll keep those ideas in mind when that time comes.

**Comment by DrumSergio** [comment]
Thank you so much, I couldn't find how to make it work!
But now the function seems outdated...

    __main__:1: DeprecationWarning: Call to deprecated function 'unwrap'. This method will be removed in version '0.9.0' Please use the 'unwrap' method on the 'hvac.api.system_backend.wrapping' class moving forward.

I tried to use it but somehow `hvac.api.system_backend.wrapping.unwrap(wrapped_token)` doesn't work.

Thank you
