### ISSUE TITLE
auth_aws_iam method fails when using any region but the default `us-east-1`

### ISSUE THREAD

**Issue by paddie** [hvac/hvac#251]
This is referencing #243 which allows for overriding the `region` in the call to `auth_aws_iam`.

It seems that setting the region to any value other than the default `us-east-1` results in an error.

I am in region `eu-west-1`, but even using `us-west-1` fails:

Here's quick snippet:

```python
    import boto3
    import hvac

    VAULT_ADDR = os.environ["VAULT_ADDR"]
    VAULT_HEADER_VALUE = os.environ["VAULT_HEADER_VALUE"]
    AWS_DEFAULT_REGION = os.environ["AWS_DEFAULT_REGION"]

    session = boto3.Session()
    creds = session.get_credentials().get_frozen_credentials()

    client = hvac.Client(url=VAULT_ADDR)

    client.auth_aws_iam(
        creds.access_key,
        creds.secret_key,
        creds.token,
        region="us-west-1",
        header_value=VAULT_HEADER_VALUE,
        role=role,
        use_token=True,
    )
```

The resulting stacktrace (below), and seems to indicate that something went wrong with the signature since it is a response from `AWS:STS` (unclear why it thinks that `us-west-1` is an invalid region though).

I am suspecting that some hard-coded region is still lingering somewhere, but I can't seem to track 
it down. I'll keep looking though.

```
Traceback (most recent call last):
  File "lambda_function.py", line 112, in <module>
    None,
  File "lambda_function.py", line 32, in lambda_handler
    vault_authenticate(header_value=VAULT_HEADER_VALUE)
  File "lambda_function.py", line 27, in vault_authenticate
    use_token=True,
  File "/usr/local/lib/python3.6/site-packages/hvac/v1/__init__.py", line 1153, in auth_aws_iam
    return self.auth('/v1/auth/{0}/login'.format(mount_point), json=params, use_token=use_token)
  File "/usr/local/lib/python3.6/site-packages/hvac/v1/__init__.py", line 1713, in auth
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/hvac/adapters.py", line 159, in auth
    response = self.post(url, **kwargs).json()
  File "/usr/local/lib/python3.6/site-packages/hvac/adapters.py", line 103, in post
    return self.request('post', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hvac/adapters.py", line 233, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/local/lib/python3.6/site-packages/hvac/utils.py", line 29, in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors)
hvac.exceptions.InvalidRequest: error making upstream request: received error code 403 from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Credential should be scoped to a valid region, not 'us-west-1'. </Message>
  </Error>
  <RequestId>12d83688-aaf1-11e8-a3f0-8f815ba4c0eb</RequestId>
</ErrorResponse>
```

Importantly, this snippet works fine:

```python
    import boto3
    import hvac

    VAULT_ADDR = os.environ["VAULT_ADDR"]
    VAULT_HEADER_VALUE = os.environ["VAULT_HEADER_VALUE"]
    AWS_DEFAULT_REGION = os.environ["AWS_DEFAULT_REGION"]

    session = boto3.Session()
    creds = session.get_credentials().get_frozen_credentials()

    client = hvac.Client(url=VAULT_ADDR)

    client.auth_aws_iam(
        creds.access_key,
        creds.secret_key,
        creds.token,
        header_value=VAULT_HEADER_VALUE,
        role=role,
        use_token=True,
    )
```

**Comment by jeffwecan** [comment]
Thanks for the bug report @paddie!  Presumably we may have missed some things in https://github.com/hvac/hvac/pull/243. I'll dig into this a bit more and get back to you in this issue.

One quick clarifying question, the first snippet of code seems to be the exact same as the bit you mentioned "works fine". Was there some difference meant to be included in that last codeblock that got left out?

**Comment by paddie** [comment]
Ach, I forgot to edit out the `region` argument. Updated one that works:

```python
    import boto3
    import hvac

    VAULT_ADDR = os.environ["VAULT_ADDR"]
    VAULT_HEADER_VALUE = os.environ["VAULT_HEADER_VALUE"]
    AWS_DEFAULT_REGION = os.environ["AWS_DEFAULT_REGION"]

    session = boto3.Session()
    creds = session.get_credentials().get_frozen_credentials()

    client = hvac.Client(url=VAULT_ADDR)

    client.auth_aws_iam(
        creds.access_key,
        creds.secret_key,
        creds.token,
        header_value=VAULT_HEADER_VALUE,
        role=role,
        use_token=True,
    )
```

**Comment by joelthompson** [comment]
Hey @paddie -- in addition to setting the region in the client, a Vault admin needs to set the [sts_endpoint](https://www.vaultproject.io/api/auth/aws/#sts_endpoint) parameter on the `config/client` endpoint for the mount to the STS endpoint for us-west-1, i.e., `sts.us-west-1.amazonaws.com`

See https://github.com/hashicorp/vault-ruby/pull/161#issuecomment-355723269 for a longer discussion as to why this is necessary.

**Comment by paddie** [comment]
@joelthompson Ahh, so the default value when setting this up inside vault and leaving out the `sts_endpoint` is `sts.amazonaws.com` that has an implied region of `us-east-1`? That is remarkable, but also wholly unsurprising from my experience with AWS services.

Maybe `hvac` or even `vault` should return something a bit more human parsable, like

```
Endpoint sts.amazonaws.com expects a region of us-east-1 not `<the-region-you-used>`. Either specify the `sts_endpoint` in the vault configuration or default to 'us-east-1' which will still enable you to auth iam roles/users (since they are global)
```

Or something. Might be easier to do in `hvac` than vault though :)

**Comment by joelthompson** [comment]
> the default value when setting this up inside vault and leaving out the sts_endpoint is sts.amazonaws.com

Yes

> that has an implied region of us-east-1?

I believe so, from my testing.

> Maybe hvac or even vault should return something a bit more human parsable

Yeah, the tricky thing there is that, to do this, Vault would need to look at the Authorization header, parse the Credential scope out of that, parse the region out of the credential scope, and then try to infer a desired region out of the STS endpoint. It would also preclude using a custom STS endpoint, or it would just have to assume the region is correct when using a custom STS endpoint. Another option might be to compute the right STS endpoint based on the region in the request, if the endpoint wasn't overridden, though there's still the open question of, when using the us-east-1 region, do you use the global STS endpoint or the regional us-east-1 STS endpoint, or is there any difference between the two?

Anyway, if you want to continue this discussion about what Vault should do, we should move it to the Vault issue tracker (it's only by coincidence that I happened to see this here).

**Comment by joelthompson** [comment]
FWIW, I think the HVAC docs could explain this caveat when overriding the region, but yeah, I don't see any easy code-side fixes.

**Comment by joelthompson** [comment]
@jeffwecan -- feel free to hit me up here or tag me in an another issue/PR if you have more questions about this.
