### ISSUE TITLE
Client.enable_auth_backend() does not support config

### ISSUE THREAD

**Issue by downeast** [hvac/hvac#252]
It looks like the [API](https://www.vaultproject.io/api/system/auth.html#enable-auth-method) accepts a config map (similar to enable_secrets) for enabling an auth method, but the `enable_auth_backends()` method does not:

```TypeError: enable_auth_backend() got an unexpected keyword argument 'config'```

Also it looks like the API accepts `plugin_name`, but the client does not.

**Comment by jeffwecan** [comment]
Ideally closed with #253 merged. Please reopen if that is not the case 😉 .

**Comment by downeast** [comment]
thanks!
