### ISSUE TITLE
Vault 0.11.0 appears to break things

### ISSUE THREAD

**Issue by DrStrangepork** [hvac/hvac#262]
I have the following policy "policy":

    # Create and manage roles
    path "auth/approle/*" {
        capabilities = ["create", "read", "list"]
    }
    # Write ACL policies
    path "sys/policy/*" {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }
    # Write test data
    path "secret/*" {
        capabilities = ["create", "read", "update", "list"]
    }
    # Manage Auth Methods
    path "auth/*" {
        capabilities = ["create", "read", "update", "delete", "sudo"]
    }

But when I try `get_policy('policy')`, I get an error:

    *** KeyError: 'rules' 

This was working fine for Vault version 0.7.* through 0.10.*

**Comment by jeffwecan** [comment]
Howdy @DrStrangepork, thanks for the report! Which hvac release are you experiencing this issue with? My initial assumption is that if you're _not_ on hvac v0.6.4, then updating to that version may see your issue resolved. In particular, I believe https://github.com/hvac/hvac/pull/254 (which was included in the 0.6.4 release) was intended to account for the error you're seeing.

**Comment by DrStrangepork** [comment]
I am using 0.6.2, but after reading #254 it does appear that it will fix my problem. I have already reverted my vault to 0.10.4, so I cannot test it, but I will assume the fix and close this issue. And update to hvac 0.6.4!
