### ISSUE TITLE
list_policy call fails with policies key not found

### ISSUE THREAD

**Issue by TerryHowe** [hvac/hvac#263]
https://github.com/hvac/hvac/blob/master/hvac/v1/__init__.py#L687

The latest version of vault does not seem to return the same json.  

There seems to be a similar change with list_auth_backends but that doesn't throw an exception.  I'll submit something if I'm not missing something.

**Comment by TerryHowe** [comment]
Hmm, list_secret_backends too

**Comment by jeffwecan** [comment]
Interesting, thanks for raising the issue @TerryHowe! For one, we're still running our integration tests here against Vault 0.10.2 (https://github.com/hvac/hvac/blob/master/scripts/install-vault-release.sh#L4). However, even with a branch running 0.11.1, I'm not seeing any test case failures to match what you're alluding to (https://travis-ci.org/jeffwecan/hvac/jobs/425804269). So in addition to tracking down what tweaks are needed, looks like we need some regression tests to make sure we have coverage against changes in these methods' responses in the future...

**Comment by TerryHowe** [comment]
https://travis-ci.org/TerryHowe/ansible-modules-hashivault/jobs/425804598

docker vault which is 0.11.0 right now

**Comment by fastest963** [comment]
I noticed an issue as well running @TerryHowe's ansible plugin. We use `hashivault_auth_enable` which ends up doing
```
backends = client.list_auth_backends()
path = (mount_point or name) + "/"
if path in backends:
```
But it looks like backends isn't the dictionary of backends anymore. Changing the `if` to
```
if path in backends['data']:
```
fixes it for us.

**Comment by alexwwang** [comment]
getting 'v1/sys/policy' from vault 0.11 will feedback a json data with key ['data'] then 2nd level key ['policies'] to list all policies' names. So the code at https://github.com/hvac/hvac/blob/master/hvac/v1/__init__.py#L687 should alter the key index correspondingly.

**Comment by jeffwecan** [comment]
FWIW: It looks like https://github.com/hvac/hvac/pull/264 will end up covering the bulk of the changed routes here. I'm hoping to have those fixes out in the v0.6.5 release of hvac which will ideally go out right around the start of October.

**Comment by jeffwecan** [comment]
FYI, I am going to re-purpose this issue to cover all routes affected by the changes in 0.11.0 in the same way.

**Comment by jeffwecan** [comment]
List of system backend methods needing an update (or not):

|Method|Update Needed?|
|----------|----------------------|
|unwrap()|No|
|is_initialized()|No|
|initialize()|No|
|seal_status()||

This is probably more comprehensive than it needs to be, but I wanted to ensure we covered all our bases.

**Comment by jeffwecan** [comment]
FWIW, part of the issue here is that the deprecation of this "top-level injection" logic was temporarily reverted in Vault v0.11.1. So I'll probably see about running the travis-ci tests against both v0.11.0 and v0.11.1 for now.

**Comment by jeffwecan** [comment]
After working through #275, I believe list_policies() is the only method in hvac that needs to be changed directly. Perhaps there could be another issue to discuss updating what ends up getting returned by methods like `list_secret_backends()` and `get_secret_backend_tuning()` since whatever change we make there will end up breaking usage one way or another?
