### ISSUE TITLE
Don't seem to be able to get AWS IAM Auth Working 

### ISSUE THREAD

**Issue by simonmacklin** [hvac/hvac#292]
Hi there 

I am trying to use the "auth_aws_iam" method to authenticate to vault with a AWS instance with a instance profile setup ready to work with vault.  The instance works fine using the vault cli but I always either get "invalid token" or "Credential should be scoped to a valid region" when trying to use this library.

Would you be able to point me where I am going wrong please.  Thanks in advanced 

First I am calling the 

```
import boto3

def get_session(region):
    """ only required when using aws iam auth """
    session = boto3.Session(region_name=region)
    return session.get_credentials()
```
then I am calling the hvac method 

```
creds = get_session('eu-west-1')
client.auth_aws_iam(access_key=creds.access_key, secret_key=creds.secret_key, role='myrole', region='eu-west-1')
```

**Comment by simonmacklin** [comment]
Sorry I have just seen the same issues logged so this can be closed 

https://github.com/hvac/hvac/issues/251

**Comment by jeffwecan** [comment]
@simonmacklin: Thanks for the report regardless! There is still a possibility it would make sense for hvac to make this specific issue more obvious to the end user, but I think I'm going to hold off on considering that for the time being and see if the updated docs are sufficient...
