### ISSUE TITLE
Hashicorp pyhton client hvac issue:- "bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed'

### ISSUE THREAD

**Issue by nkv16786** [hvac/hvac#295]
I am using the following config.hcl for my Hashicorp server,
disable_mlock = true

```
storage "file" {
  path = "/etc/secrets"
}

listener "tcp" {
 address     = "10.xx.xx.xx:8200"
 tls_cert_file = "/etc/certs/selfsigned.crt"
 tls_key_file  = "/etc/certs/selfsigned.key"
```
it is working fine when i perform vault operations, But when i try reach it using hvac python library i am getting SSL error. The code i am using to connect to hashicorp server from python is,
```
import hvac
client = hvac.Client(url='https://10.xx.xx.xx:8200', cert=('/etc/certs/selfsigned.crt', '/etc/certs/selfsigned.key'))
client.token = 'd460cb82-08aa-4b97-8655-19b6593b262d'
client.is_authenticated() 
```

The full error trace i am getting is as follows:-
`Traceback (most recent call last): File "", line 1 , in File "/usr/local/lib/python2.7/dist-packages/hvac/v1/init.py", line 552, in is_authenticated self.lookup_token() File "/usr/local/lib/python2.7/dist-packages/hvac/v1/init.py", line 460, in lookup_token return self._get('/v1/auth/token/lookup-self', wrap_ttl=wrap_ttl).json() File "/usr/local/lib/python2.7/dist-packages/hvac/v1/init.py", line 1236, in _get return self.request('get', url, **kwargs) File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init.py", line 1264, in __request allow_redirects=False, **_kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 511, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='10.xx.xx.xx', port=8200): Max retries exceeded with url: /v1/auth/token/lookup-self (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

**Comment by jeffwecan** [comment]
If its indeed a self-signed certificate in play, you may need to inform the underlying requests module where to find the CA for your self-signed cert (or less ideally, pass `verify=False` to the Client constructor). Maybe check out the relevant documentation and see if it covers your use case?: https://hvac.readthedocs.io/en/v0.6.4/advanced_usage.html#making-use-of-private-ca

**Comment by nkv16786** [comment]
Hi, I had some issues with the configuration and it started working when i changed it .
But it is only working when i am using hvac from same host if i try to connect it from remote host again i am getting the same error:-

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 603, in is_authenticated
    self.lookup_token()
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 508, in lookup_token
    return self._get(path, wrap_ttl=wrap_ttl).json()
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 1458, in _get
    return self.__request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 1486, in __request
    allow_redirects=False, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

On my hashicorp server i am seeing,

`2018-10-19 00:25:57.279547 I | http: TLS handshake error from 10.xx.xx.xx:48734: remote error: tls: unknown certificate authority`

**Comment by jeffwecan** [comment]
This looks like a problem with your certificate generally @nkv16786...

What operating system flavor and version is your Vault cluster running on? Was your self-signed cert signed by a self-signed CA cert? If so, was that CA cert added to the default CA store for the operating system that Vault server process(es) are running on?

Ultimately this seems like a problem with the way the certificate in question was issued and/or how the runtime environment is configured (in terms of recognizing the validity of that certificate) for the Vault cluster / hvac rather than an issue with hvac itself.

**Comment by nkv16786** [comment]
Hi,
The issue got resolved. You were right, the problem was with the cert configurations only.
Thanks :)

**Comment by nkv16786** [comment]
Hi,
You were right. The problem was with cert configuration only.
The issue is resolved now hence closing

**Comment by nkv16786** [comment]
Hi,
You were right. The issue was with cert configuration only.
This issue is resolved now. 
You can close this.

Thanks :)
