### ISSUE TITLE
Support for Transit engine?

### ISSUE THREAD

**Issue by alexandernst** [hvac/hvac#302]
Are there any plans to support Transit engine?

**Comment by jeffwecan** [comment]
We're looking to implement explicit support for all available Vault API routes at some point. So generally, yes. :P

I can move Transit towards the top of the backlog though!

**Comment by alexandernst** [comment]
Yes, please! We're looking towards using Transit. In fact, we'd like to contribute if that will speed up things.

**Comment by jeffwecan** [comment]
Feel free to contribute whatever you'd like; that is always very appreciated! Unfortunately, we don't have a great contributing doc around adding new classes along these lines at the moment. However using recent PRs like https://github.com/hvac/hvac/pull/244 or https://github.com/hvac/hvac/pull/257 as examples would hopefully provide enough of a framework to get started with.

I also have a work-in-progress script to stub out hvac classes based on vaultproject.io documentation. So if you want to use the output of that script as a launching off point, check out this branch on my fork: https://github.com/hvac/hvac/compare/master...jeffwecan:transit_secret_engine_class?expand=1

**Comment by jeffwecan** [comment]
Closed by #303.
