### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'sys'

### ISSUE THREAD

**Issue by jinsiang2008** [hvac/hvac#332]
Hi there,

I am using hvac version 0.6.4, when I call the vault_client. sys.list_leases(), I got:
`vault_client.sys.list_leases(
AttributeError: 'Client' object has no attribute 'sys'`

I think system backend was enabled in hvac 0.6.2? So, not really sure what's the problem is? Might be a bug?

Thank you.
Sam

**Comment by jeffwecan** [comment]
The `sys` attribute itself was added in hvac v0.7.0. Try bumping your requirements to that version and let us know if you're still seeing issues? Assuming that does the trick, we can review the documentation and see if that fact needs to be called out more clearly...

**Comment by jinsiang2008** [comment]
Will do and let you know, thanks @jeffwecan 
The doc is here: https://hvac.readthedocs.io/en/latest/usage/system_backend/lease.html

**Comment by jeffwecan** [comment]
Ah, thanks! I do see the confusion. There were various lease methods added in 0.6.2, but the new way of addressing them (via the `sys` property) was added in 0.7.0. I'll see what we can do about clearing up that confusion moving forward! 👍
