### ISSUE TITLE
Support /sys/capabilities System Backend

### ISSUE THREAD

**Issue by viralpoetry** [hvac/hvac#335]
Hi,
It would be nice to have /sys/capabilities API endpoint so one can request token capabilities.
https://www.vaultproject.io/api/system/capabilities.html

I consider it a "good first issue" and eventually will push MR by myself if I find a time.

Thank you!

**Comment by jeffwecan** [comment]
@viralpoetry, makes sense! I'll scope it out myself the next time I get a change to work through some of our issues here but if you beat me to it, all the better! ;)
