### ISSUE TITLE
Namespaces does not work with approle authentication

### ISSUE THREAD

**Issue by drewmullen** [hvac/hvac#336]
namespaces does not work when authing via approle

failing:
```
import hvac

role_id = '<valid role id>'
secret_id = '<valid secret id>'

client = hvac.Client(
    url='https://vault.example.com:8200',
    verify=False,
    namespace='namespace/a'
    )

client.auth_approle(role_id, secret_id)
print(client.is_authenticated) 

print(client.read('secret/data/name'))
```
error:
```
Traceback (most recent call last):
  File "auth_approle.py", line 27, in <module>
    client.auth_approle(role_id, secret_id)
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1428, in auth_approle
    return self.login('/v1/auth/{0}/login'.format(mount_point), json=params, use_token=use_token)
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1191, in login
    **kwargs
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/adapters.py", line 177, in login
    response = self.post(url, **kwargs).json()
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/adapters.py", line 106, in post
    return self.request('post', url, **kwargs)
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/adapters.py", line 265, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/home/rmullen/.local/lib/python2.7/site-packages/hvac/utils.py", line 29, in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors)
hvac.exceptions.InvalidRequest: missing client token
```

working without namespace:
```
import hvac

role_id = '<valid role id>'
secret_id = '<valid secret id>'

client = hvac.Client(
    url='https://vault.example.com:8200',
    verify=False #,
    #namespace='namespace/a'
    )

client.auth_approle(role_id, secret_id)
print(client.is_authenticated)

#print(client.read('secret/data/name'))

print(client.read('secret/data/test'))
```

working output:
```
{u'lease_id': u'', u'warnings': None, u'wrap_info': None, u'auth': None, u'lease_duration': 0, u'request_id': u'2a384059-ea2b-da20-c231-de7bdd126cc6', u'data': {u'data': {u'bye': u'bye$bye', u'hello': u'world'}, u'metadata': {u'created_time': u'2018-10-25T06:30:37.998323236Z', u'destroyed': False, u'version': 3, u'deletion_time': u''}}, u'renewable': False}
```

**Comment by jeffwecan** [comment]
@drewmullen: Just out of curiosity, is there a way to test namespace functionality without actually having a full Vault enterprise cluster? Would be handy to be able to add regression tests within hvac for this type of functionality...

**Comment by drewmullen** [comment]
https://github.com/hvac/hvac/blob/a609d8fdbc1f3db5126f44fd98964b869c9b850c/hvac/v1/__init__.py#L1563

**Comment by drewmullen** [comment]
@jeffwecan i believe it was open sourced recently 

https://www.vaultproject.io/docs/commands/namespace.html

**Comment by drewmullen** [comment]
i think its simpler, auth_approle just doesnt accept namespace as an arg

https://github.com/hvac/hvac/blob/a609d8fdbc1f3db5126f44fd98964b869c9b850c/hvac/v1/__init__.py#L1408

**Comment by drewmullen** [comment]
I think its worth showing that it **does** work with auth_method=LDAP and pre-auth'ed tokens

**Comment by drewmullen** [comment]
im still pretty new to python but... heres what i gathered so far:
new Adapters class object is instantiated and sets 
```
self._adapter = adapters.
    ...
    namespace=namespace
```

then, when i invoke `client.auth_approle(role_id, secret_id)`  it passes (url endpoint, role_id, secret_id, use_token) to adapters/login

login passes the same to adapters/post

post passes url and the other args as kwargs to adapters/request

request receives method, url, kwargs, and headers which defaults to None... 
assuming headers DOES = None (since app_role cant even pass that dict) it then defines the headers
and, i believe **should** have access to self.namespace from the Adapter class object instantiated during the Client object creation (above)

can someone check my math on this?

**Comment by drewmullen** [comment]
as far as the passed parameters go, the only difference is:
without namespace, headers={}
with namespace, headers={"X-Vault-Namespace": "<my ns>"}

**Comment by drewmullen** [comment]
gha.

hvac does not appear to be the issue. my approle / namespaces weren't setup correctly (getting false positives in my testing) and the ansible PR shippable test error was nearly identical to the error i was getting locally. 

closing this issue as i dont think the ansible PR issue has to do with HVAC, likely has to do with their automated testing
