### ISSUE TITLE
Question regarding Github auth method

### ISSUE THREAD

**Issue by PseudotsugaMeziesii** [hvac/hvac#338]
For whatever reason, the docs for Github auth were totally confusing to me. I'm a total newb with respect to Vault, so that cant help...

I've been able to get the module to do what I needed, but was hoping to get some feedback if I'm using it as intended:

>import hvac

>token = '<github_token_goes_here>'
>github_path = 'github_my-team'
>client = hvac.Client(url='https://vault.mysite.org:1234')
>hvac.v1.api.auth_methods.Github(client.adapter).login(token, mount_point=github_path)

>my_secret = client.read('secret/my-team/foo')['data']['secret']

That the baseline means of retrieving a secret using Github for auth?

**Comment by jeffwecan** [comment]
Howdy @PseudotsugaMeziesii! The documentation for this auth method (and all implemented auth methods generally) definitely could use some more holistic examples. I can see about getting those usage docs expanded in the near term. Real quick though: looking at your example the main issue I see is that you're calling the GitHub class directly. Instead, most interaction with Vault using this module is done via the `Client` class. I.e., in your example code:

```python
# ...
client = hvac.Client(url='https://vault.mysite.org:1234')
hvac.v1.api.auth_methods.Github(client.adapter).login(token, mount_point=github_path)
``` 

should instead be something like:

```python
# ...
client = hvac.Client(url='https://vault.mysite.org:1234')
client.auth.github.login(token, mount_point=github_path)
# => client instance now has a Vault token retrieved via the GitHub auth method
```

Does that help get ya pointed in the right direction?

**Comment by PseudotsugaMeziesii** [comment]
Thanks, @jeffwecan! It seemed odd to me to have to leverage the Github class that way, especially when everything else was using the client object. Embarrassingly, I even recall seeing your suggestion as as one of the deprecation messages while I was testing. It didn't 'walk' out in my IDE so I didn't actually tryy it out. Sheesh.

Thanks, again!
