### ISSUE TITLE
illegal base64 client.auth.gcp.login

### ISSUE THREAD

**Issue by burbma** [hvac/hvac#345]
Trying to authenticate with Vault via GCP jwt. The code to generate the jwt is found here https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/clients/google-jwt-client.py#L29
```python
import google.auth.crypt
import google.auth.jwt
import hvac

signer = google.auth.crypt.RSASigner.from_service_account_file(path_to_sa_json)
now = int(time.time())
expires = now + 3600  # One hour in seconds
payload = {
    'iat': now,
    'exp': expires,
    'sub': 'service-account@my-project.iam.gserviceaccount.com',
    'aud': 'vault/my-role'
}
jwt = google.auth.jwt.encode(signer, payload).decode('utf-8')

client = hvac.Client(url='vault.example.com', verify='path/to/ca.pem')
client.auth.gcp.login('my-role', jwt)
```

The call to `client.auth.gcp.login('my-role', jwt)` returns
```
hvac.exceptions.InvalidRequest: illegal base64 data at input byte 190
```

I did some more digging. If I take the `jwt` generated with the Python code above and run
```bash
vault write -field=token auth/gcp/login role=my-role jwt=<jwt-from-above>
```
I again get `illegal base64 data at input byte 190` but this time it's directly from Vault so I cut out the possibility that hvac is the problem.

Next I tried generating a jwt with `gcloud` via (near the bottom of https://cloud.google.com/solutions/using-vault-for-secret-management)
```bash
GOOGLE_PROJECT=$(gcloud config get-value project)
SERVICE_ACCOUNT=my-service-account@${GOOGLE_PROJECT}.iam.gserviceaccount.com
cat - > login_request.json <<EOF
{
    "aud": "vault/my-role",
    "sub": "${SERVICE_ACCOUNT}",
    "exp": $((EXP=$(date +%s)+600))
}
EOF
export JWT_TOKEN=$(gcloud beta iam service-accounts sign-jwt login_request.json \
    signed_jwt.json \
    --iam-account=${SERVICE_ACCOUNT} && cat signed_jwt.json)
```
Then I used that jwt to do
```bash
vault write -field=token auth/gcp/login role=my-role jwt=$JWT_TOKEN
```
and it worked!

So in the end the problem is not with hvac. It's in google or more likely my use of google's code being incorrect.

**Comment by burbma** [comment]
It makes sense that the `signature` can't be base64 decoded straight away since during the signing process it was run through HMACSHA256 with a secret. If I understand correctly the secret is the GCP service account. So then is `hvac` missing or not finding something, like the service account, that it needs to make sense of the `signature`?

**Comment by burbma** [comment]
It would appear that the way I'm generating the JWT is the issue. I generated one with `gcloud` on the command line as per instructions found near the bottom of https://cloud.google.com/solutions/using-vault-for-secret-management.

**Comment by burbma** [comment]
I'll close the issue as the problem is not with `hvac`, well I never though there was a problem, just my ignorance. But now I see that my ignorance is not how to use `hvac` but how to generate the JWT.

**Comment by jeffwecan** [comment]
@burbma Seems like it might be worth calling out this scenario in the hvac docs at least to potentially help out folks that find the same pitfall in the future no? Assuming you agree, I'll leave this issue open with the scope being said doc updates. 👍

**Comment by burbma** [comment]
Here's the working version
```python
import googleapiclient.discovery # pip install google-api-python-client
import google.oauth2 # pip install google-auth
import hvac # pip install hvac

with open(path_to_sa_json, 'r') as f:
    creds = json.load(f)
    project = creds['project_id']
    service_account = creds['client_email']

now = int(time.time())
expires = now + 900  # 15 mins in seconds, can't be longer.
payload = {
    'iat': now,
    'exp': expires,
    'sub': service_account,
    'aud': 'vault/my-role'
}

credentials = google_service_account.Credentials.from_service_account_file(path_to_sa_json)
iam = googleapiclient.discovery.build('iam', 'v1', credentials=credentials)
name = f'projects/{project}/serviceAccounts/{service_account}'
body = {'payload': json.dumps(payload)}
request = iam.projects().serviceAccounts().signJwt(name=name, body=body)
resp = request.execute()
jwt = resp['signedJwt']
client.auth.gcp.login('my-role', jwt)
```
