### ISSUE TITLE
permission denied while trying to write or read secret

### ISSUE THREAD

**Issue by meet101** [hvac/hvac#349]
I am able to successfully write and read secrets using CLI. I am trying to make it work with HVAC library. I am able to create a client with token and authenticate token but when I try to write or read secrets I am getting permission denied error. 
can someone please advise what am I doing wrong?

ubuntu@ip-xx-xx-xx-xx~$ python test-vault.py 
Traceback (most recent call last):
  File "test-vault.py", line 7, in <module>
    print(client.read('secret/password'))
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 195, in read
    return self._adapter.get('/v1/{0}'.format(path), wrap_ttl=wrap_ttl).json()
  File "/usr/local/lib/python2.7/dist-packages/hvac/adapters.py", line 93, in get
    return self.request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hvac/adapters.py", line 265, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/local/lib/python2.7/dist-packages/hvac/utils.py", line 33, in raise_for_error
    raise exceptions.Forbidden(message, errors=errors)
hvac.exceptions.Forbidden: permission denied

Getting same error while I try to write secret as well. 
here is my code,

import hvac
client = hvac.Client(url="http://xx.xx.xx.xx:8200", token="xxxx-xxxx-xxxx-xxxx-xxxx")
#client.write('secret/foo', baz="bar")
print(client.read('secret/password'))

**Comment by meet101** [comment]
I figured out this issue. It was not actually an issue. I was using default policy and that doesn't have write and read capabilities. I created custom policy and seems working fine.

**Comment by git-chakra** [comment]
@meet101  I am facing the same problem, and used a custom policy file with "read" capabilities, but didnt work. 
kindly suggest how you created custom policy. 
I am using hvac version 0.2.17. (have to use it, can not update)

**Comment by meet101** [comment]
@git-chakra can you share custom policy that you created? Make sure you added correct path and write operation.

**Comment by git-chakra** [comment]
@meet101 below is 'my-policy' that I created, 

path "secret/*" {
    capabilities = ["create", "read", "update", "list"]
}

and my token has both 'default' and 'my-policy' policies

however, i get 'permission denied' on reading a secret as below:
client.read('secret/foo_user')
