### ISSUE TITLE
Cannot set length of random bytes in transit.generate_random_bytes()

### ISSUE THREAD

**Issue by kserrano** [hvac/hvac#376]
No matter what the value 'n_bytes' is, the random bytes are always 32 bytes, which is the default value.
Assuming you have a valid token :
`client.secrets.transit.generate_random_bytes(n_bytes=length,output_format='hex')['data']['random_bytes']`
returns 32 bytes, independently of the value 'n_bytes'

**Comment by jeffwecan** [comment]
Closed by https://github.com/hvac/hvac/pull/377?
