### ISSUE TITLE
Invalid Path Warning Returned When Writing to KV Secrets Engine Using Client.write()

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#378]
Via an emailed question:

> I'm trying to write a secret to the key/val store, following the hvac readme in github I've tried client.write('secret/foo', baz='bar', lease='1h')
but keep getting an error message 
>
> "{"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put' for this operation."],"auth":null}"
>
> Is this version of write depreciated? 
I can make a PR for the readme and update it to the new way to write a secret if you're open to pointing me in the right direction.

**Comment by jeffwecan** [comment]
Howdy!

It sounds like you would need to either restructure how your invoking `Client.write()` here to match the [KV version 2 API specifications](https://www.vaultproject.io/api/secret/kv/kv-v2.html#create-update-secret) or simply use the explicit KV v2 hvac support as outlined here:  https://hvac.readthedocs.io/en/stable/usage/secrets_engines/kv.html / https://hvac.readthedocs.io/en/stable/usage/secrets_engines/kv_v2.html

For context:

* Recent releases of Vault default to enabling the **KV version 2** secrets engine under the `secret/` path by default.
* The `Client.write()` method with this module is generally meant to be an analog to the `vault write` CLI command. I.e., you can expect to see generally the same behavior in the CLI version of things as you would with the hvac method.

To be clear, updating your current statement from `client.write('secret/foo', baz='bar', lease='1h')` to `client.secrets.kv.create_or_update_secret(path='secret/foo', secret=dict(baz='bar))` should be the general way to go about resolving things. However please do let us know if you have any further questions.

With all that said, I'll intend to use this issue as a bookmark to update the current README.md contents with a callout about the difference between KV v1 versus v2 behavior (we certainly want the Getting Started section to actually succeed in getting folks started :D).

**Comment by wmcg** [comment]
As a new user to Vault and hvac, following the getting started in the readme got me stuck at this issue. +1 for an update to the readme.
