### ISSUE TITLE
parsing response from vault to useful python collection

### ISSUE THREAD

**Issue by drewmullen** [hvac/hvac#382]
I'm having a problem parsing hvac responses, i dont think this is necessarily a problem with hvac but im wondering if anyones solved this problem before or has an eloquent recommendation because **i dont like my current solution.**

example response:
```
{u'lease_id': u'', u'warnings': None, u'wrap_info': None, u'auth': None, u'lease_duration': 0, u'request_id': u'81-scrambled-5f-c21b4844b75c', u'data': {u'keys': [u't1', u't2', u'tf/']}, u'renewable': False}
```
what i want to extract:
key_list = `['t1', 't2', 'tf/']`

**current working solution**
```
r = client.secrets.kv.v2.list_secrets('test', mount_point='secret')
key_list = ast.literal_eval(json.dumps(json.loads(json.dumps(r))[u'data'][u'keys']))
```

**Things i noticed**
typical solution:
```
key_list = ast.literal_eval(json.dumps(client.secrets.kv.v2.list_secrets('test', mount_point='secret'))).data.keys[:]
ERROR: 'malformed string'
```
the problem is that json.dumps() converts `None` and `False` to `null` and `false` which `literal_eval` cannot parse ("Error: Malformed string")

`ast.literal_eval()` alone wont work because it cannot parse the original unicode response "malformed string"

`key_list = json.dumps(r).data` wont work because r is now a `str` and not a `dict`

**Comment by drewmullen** [comment]
after looking into this more, this seems like a solvable problem with a shareable solution. from json lib docs: `To use a custom JSONEncoder subclass (e.g. one that overrides the default() method to serialize additional types), specify it with the cls kwarg; otherwise JSONEncoder is used.`

so we could create a subclass encoder and include with HVAC that you could invoke with a kwarg when using json.dumps like `json.dumps(cls=vault_encoder, my_json_blob)`

https://github.com/python/cpython/blob/bf4ac2d2fd520c61306b2676db488adab9b5d8c5/Lib/json/encoder.py#L390

is this interesting to anyone else or something you'd consider including with the project? I could look into this more if it is

**Comment by jeffwecan** [comment]
I do find the idea of providing some mechanism that allows the optional use of custom JSONEncoder class(es) intriguing!

To the initial content of this issue, I am a smidge confused. hvac pretty much across the board returns native Python types. So with your example statement:

```python
r = client.secrets.kv.v2.list_secrets('test', mount_point='secret')
```

My go-to solution would be something as simple as this:

```python
key_list = r['data']['keys']
```

Does that help clear things up or am I indeed missing something? Regardless of the answer, I would still be intrigued to explore solutions like JSONEncoder. In particular, I find addressing specific fields out of full Vault response somewhat onerous. E.g., when reading a secret from a KV v2 engine:

```python
read_response = client.secrets.kv.read_secret_version(path='secret/foo')
print('Value under path "foo" / key "baz": {val}'.format(
   val=read_response['data']['data']['baz'],
))
```

The `read_response['data']['data']` bit is not so easy on the eyes...

**Comment by drewmullen** [comment]
`key_list = r['data']['keys']` this actually worked for me too... I think i may have used jinja syntax (dot notation) on accident since, the problem im solving is for a new ansible module. phew. glad its easier than i originally thought

I actually got kind of excited about working with JSONEncoder too lol... so in your thoughts, would you reorganize the response object? ex: place the` ['data']['data']['baz']` available at `['keys']['baz']` instead or just `['baz']`?

**Comment by drewmullen** [comment]
ill close this for now... if you think theres an opportunity here to extend the class, lmk what you think. i dont have an immediate need but i do see it as an fun potential project to work on

thanks for the help
