### ISSUE TITLE
client.secrets.kv.list_secrets only lists one secret

### ISSUE THREAD

**Issue by alpozcan** [hvac/hvac#386]
Hi,
On Vault web interface, path A/B/C is shown to hold three secrets X, Y, Z.
When `client.secrets.kv.list_secrets` is called on a path A/B/C, only Y is returned under ['data']['keys'].

`client.secrets.kv.default_kv_version` is set to '1', hvac version is 0.7.2 running on Python 3.7.2. The same auth method and token is used in the code that uses hvac and for logging into the web interface.

Is this the intended behaviour and I am missing something, or a bug?

**Comment by jeffwecan** [comment]
hvac is simply passing on the response from Vault in this instance. I can see about trying to replicate the issue and report back however.

**Comment by alpozcan** [comment]
We had paths with identical names but '/' suffix at the end for some of them. X/Y/Z had only one secret but X/Y/Z/ had multiple ones but the client was always reading the former due to the way paths are used in the requested.
The confusion seems to have been caused by this idiosyncrasy in our data.
