### ISSUE TITLE
Database Engine

### ISSUE THREAD

**Issue by hydratim** [hvac/hvac#387]
Hey, 

Is there a reason that the Database engine isn't supported yet?
Is there an ETA?

Thanks,
Tim.

**Comment by hydratim** [comment]
Cool, I'd make a PR, but my open-source time is dedicated elsewhere ATM. So I'm glad it's on the roadmap already!

**Comment by blancsys** [comment]
@hydratim Hi Tim, the database secret engine support was merged yesterday and it's arriving on 0.8.3 (https://github.com/hvac/hvac/pull/431)

**Comment by hydratim** [comment]
Fantastic!
