### ISSUE TITLE
sts cred generation fails due to wrong method usage

### ISSUE THREAD

**Issue by spbsoluble** [hvac/hvac#391]
When trying this:
`
vault_client.secrets.aws.generate_credentials(
            name="ReadOnly",
            mount_point="aws-lab",
            endpoint="sts",
)
`
The vault will return a 401 because it's expecting POST rather than GET.

**Comment by jeffwecan** [comment]
Closing this out as I believe #392 was sufficient to resolve things. Feel free to reopen the issue if I am mistaken though!
