### ISSUE TITLE
Error renewing token

### ISSUE THREAD

**Issue by DrumSergio** [hvac/hvac#397]
Hi, I have a problem while using the hvac client

First of all, thank you for making this software real!

Very simple script:

```
#!/usr/bin/python3
import os
import hvac

VaultURL = os.environ['VAULT_ADDR']
CurrentToken = os.environ['VAULT_TOKEN']

client = hvac.Client(url=VaultURL, token=CurrentToken)
client.sys.renew_token(CurrentToken)
```
I simply tried with `client.sys.renew_token()`  also but it fails also with the same error.

```
Traceback (most recent call last):
  File "vault-renew-token.py", line 9, in <module>
    client.sys.renew_token(CurrentToken)
  File "/usr/local/lib/python3.5/dist-packages/hvac/api/system_backend/__init__.py", line 58, in __getattr__
    raise AttributeError
```

If I can provide you more info I can.

Thank you very much!

**Comment by jeffwecan** [comment]
The API route you're after is currently handled by a method attached to the client class. I.e., I believe updating the `client.sys.renew_token(CurrentToken)` to `client.renew_token(CurrentToken)` would do the trick.
