### ISSUE TITLE
Unable to authenticate on AWS Lambda

### ISSUE THREAD

**Issue by soapergem** [hvac/hvac#399]
I was able to get HVAC authenticating successfully when running on an EC2 instance. However, I am seemingly not able to get the same code working on Lambda. Since I see a number of past issues relating to Lambda, as well as [examples in the docs](https://hvac.readthedocs.io/en/latest/usage/auth_methods/aws.html#lambda-and-or-ec2-instance), I assume this should be supported. However I suspect some of the examples may be slightly outdated. I'm wondering if perhaps something has changed?

Here's the main body of my Lambda function:

```python
import hvac
import logging
import os


logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def handler(event, context):
    client = hvac.Client(url="https://vault.mydomain.com")
    client.auth_aws_iam(
        access_key=os.getenv("AWS_ACCESS_KEY_ID"),
        secret_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        session_token=os.getenv("AWS_SESSION_TOKEN"),
        header_value="vault.mydomain.com",
        role='my-vault-role',
    )

    secrets = client.read("secret/path/to/my/secrets")
    values = secrets.get("data")
    logger.info(values)
    return {"body": values}
```

The reason I said that the examples are slightly outdated is because they don't include `AWS_SESSION_TOKEN`, which AFAIK is always present on Lambda functions, these days.

The error message I get says **failed to verify `my-test-func` as a valid EC2 instance in region us-east-1**, but I'm not using EC2 authentication (I am using IAM authentication). Here's the stack trace:

```
failed to verify my-test-function as a valid EC2 instance in region us-east-1: InvalidRequest
Traceback (most recent call last):
  File "/var/task/lambda.py", line 18, in handler
    role='my-vault-role',
  File "/var/task/hvac/v1/__init__.py", line 638, in auth_aws_iam
    return self.login('/v1/auth/{0}/login'.format(mount_point), json=params, use_token=use_token)
  File "/var/task/hvac/v1/__init__.py", line 1191, in login
    **kwargs
  File "/var/task/hvac/adapters.py", line 177, in login
    response = self.post(url, **kwargs).json()
  File "/var/task/hvac/adapters.py", line 106, in post
    return self.request('post', url, **kwargs)
  File "/var/task/hvac/adapters.py", line 276, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/var/task/hvac/utils.py", line 29, in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors)
hvac.exceptions.InvalidRequest: failed to verify my-test-function as a valid EC2 instance in region us-east-1
```

The weird thing is that if I run what is basically the same code, on an EC2 instance, it works fine. Specifically, this is the code that I have running on EC2:

```python
import hvac
import logging
import requests


logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def load_aws_ec2_role_iam_credentials():
    # first get the IAM role we are currently operating under
    url = "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
    response = requests.get(url)
    response.raise_for_status()
    current_role = response.text

    # then look up STS credentials
    url = f"http://169.254.169.254/latest/meta-data/iam/security-credentials/{current_role}"
    response = requests.get(url)
    response.raise_for_status()
    security_credentials = response.json()
    return security_credentials


creds = load_aws_ec2_role_iam_credentials()
client = hvac.Client(url="https://vault.mydomain.com")
client.auth_aws_iam(
    access_key=creds.get("AccessKeyId"),
    secret_key=creds.get("SecretAccessKey"),
    session_token=creds.get("Token"),
    header_value="vault.mydomain.com",
    role='my-vault-role',
)

secrets = client.read("secret/path/to/my/secrets")
values = secrets.get("data")
logger.info(values)
```

That code successfully prints out the secrets that I have set at that path. Both the Lambda and the EC2 code are running under the same role / instance profile. The only thing observably different about the code is how they retrieve their STS access keys, which is per the HVAC documentation. Since the error message says that it fails to verify my Lambda function as a valid EC2 instance, I'm wondering if I missed setting some kwarg or function call in HVAC?

It may also be worth noting that in this is a cross-account scenario. Vault lives in one account, whereas this code (both Lambda and EC2) live in a separate AWS account. I have roles set up on both sides which allows Vault to authenticate and validate my EC2 instances. Clearly, though, I know this setup works (just not on Lambda), as evidenced by the fact that my code on EC2 runs fine.

The cross-account role which Vault ultimately assumes has the following permissions: `ec2:DescribeInstances`, `iam:GetRole`, `iam:GetInstanceProfile`, and `iam:GetUser`. For good measure I just added in `lambda:ListFunctions`, though unfortunately that didn't solve the problem. Any ideas?

**Comment by soapergem** [comment]
The comment I wrote above involved a cross-account scenario. Forgetting that for a second, I can't even seem to get HVAC working on just one account. This is the Lambda function code I'm trying:

```python
import hvac
import os

def handler(event, context):
    client = hvac.Client(url="https://vault.mydomain.com")
    client.auth_aws_iam(
        access_key=os.getenv("AWS_ACCESS_KEY_ID"),
        secret_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        session_token=os.getenv("AWS_SESSION_TOKEN"),
        header_value="vault.mydomain.com",
        role="my-vault-role",
    )

    secrets = client.read("secret/path/to/my/secrets")
    values = secrets.get("data")
    return {"body": values}
```

However that doesn't even work. The error I'm getting now is `failed to verify <lambda-func> as a valid EC2 instance in region us-east-1` where `<lambda-func>` is the name of my Lambda function. **Can anyone provide a working example block of code for using HVAC in Lambda please?**

**Comment by jhmartin** [comment]
Can you post the Vault configuration for this role? It sounds to me like the inferencing function is trying to map your IAM role to an instance.

**Comment by soapergem** [comment]
I finally figured it out over the weekend, and was meaning to post a follow-up. The issue is not with HVAC but as you correctly suspected; it lay entirely with how I had Vault configured. I've been using Terraform for my Vault roles and policies. Here is the correct configuration for a Vault role that finally got this working:

```hcl
resource "vault_policy" "my-lambda-policy" {
  name   = "my-lambda-policy"
  policy = "${file("policy.hcl")}"
}

resource "vault_aws_auth_backend_role" "my-lambda-role" {
  backend                  = "aws"
  role                     = "my-vault-role"
  auth_type                = "iam"
  bound_iam_principal_arns = ["arn:aws:iam::1234567890:role/lambda_basic_execution"]
  ttl                      = 60
  max_ttl                  = 120
  policies                 = ["${vault_policy.my-lambda-policy.name}"]
}
```

Whereas here was the configuration I had been trying which worked on EC2 but failed on Lambda:

```hcl
resource "vault_policy" "my-ec2-policy" {
  name   = "my-ec2-policy"
  policy = "${file("policy.hcl")}"
}

resource "vault_aws_auth_backend_role" "my-ec2-role" {
  backend                         = "aws"
  role                            = "my-vault-role"
  auth_type                       = "iam"
  bound_iam_role_arns             = ["arn:aws:iam::1234567890:role/ec2_role"]
  bound_iam_instance_profile_arns = ["arn:aws:iam::1234567890:role/ec2_instance_profile"]
  ttl                             = 60
  max_ttl                         = 120
  policies                        = ["${vault_policy.my-ec2-policy.name}"]
}
```
