### ISSUE TITLE
newbie problem in reading secret from k8s

### ISSUE THREAD

**Issue by Marianna-Cattani** [hvac/hvac#401]
Hi, I'm inside a kubernetes pods, I'm not able to read a secret, I have a bit more luck with CLI.

`
root@kubernetes-pods:/# pip3 list | grep hvac      
hvac              0.7.2     
root@kubernetes-pods:/# python3
Python 3.7.2 (default, Jan  3 2019, 02:55:40) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import hvac
>>> f = open('/var/run/secrets/kubernetes.io/serviceaccount/token')
>>> jwt = f.read()
>>> client = hvac.Client()
>>> client = hvac.Client(url='https://vault.mydomain.zone')
>>> client.auth_kubernetes("default", jwt)
{'request_id': '0f69ff6c-670b-5d4f-8173-fc200f2d3f03', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': None, 'wrap_info': None, 'warnings': None, 'auth': {'client_token': '1ec8ec13-a3f1-d775-1a05-1d3c0ed569f6', 'accessor': 'ac2a8a0b-2fab-fde6-5806-0ca246baeaec', 'policies': ['default', 'default-auth'], 'metadata': {'role': 'default', 'service_account_name': 'default', 'service_account_namespace': 'default', 'service_account_secret_name': 'default-token-2gq9p', 'service_account_uid': 'c9a4ebb8-0b27-11e8-be3e-02d3a780ab08'}, 'lease_duration': 60, 'renewable': True, 'entity_id': '0d0ff9de-e26c-7b9f-7b56-0e2135137c71'}}
>>> print(client.read('secret/pippo/pluto'))
None
>>> 
root@kubernetes-pods:/#  export VAULT_ADDR=https://vault.mydomain.zone
root@kubernetes-pods:/#  export VAULT_TOKEN=091c673e-e169-73dc-95b3-c085332ba3a6
root@kubernetes-pods:/# ./vault version
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
root@kubernetes-pods:/# ./vault kv get secret/pippo/pluto
====== Metadata ======
Key              Value
---              -----
created_time     2019-03-04T13:55:15.987003457Z
deletion_time    n/a
destroyed        false
version          40

====================== Data ======================
Key                                         Value
---                                         -----
pass      			                CExG3yDwuKA4cwnj
user                			      keyuser2
keyid       						ACC-KEY1
root@kubernetes-pods:/# 
`

Please can you point me to the right direction to solve this ?

**Comment by jeffwecan** [comment]
Is the secrets engine mounted under the `secret/` KV version 1 or version 2? If it is version 2, you'll want to use the hvac methods outlined here: https://hvac.readthedocs.io/en/stable/usage/secrets_engines/kv_v2.html

**Comment by Marianna-Cattani** [comment]
...oh, this looks much better:

>>> client.auth_kubernetes("default", jwt)
{'request_id': 'e842c81b-ea6e-59f8-95fb-36a5f8fc3595', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': None, 'wrap_info': None, 'warnings': None, 'auth': {'client_token': '9bbcaf70-514d-406b-6b82-858ca098cf59', 'accessor': 'fcc71367-1231-c704-1a69-b78ce6d1c80a', 'policies': ['default', 'default-auth'], 'metadata': {'role': 'default', 'service_account_name': 'default', 'service_account_namespace': 'default', 'service_account_secret_name': 'default-token-2gq9p', 'service_account_uid': 'c9a4ebb8-0b27-11e8-be3e-02d3a780ab08'}, 'lease_duration': 60, 'renewable': True, 'entity_id': '0d0ff9de-e26c-7b9f-7b56-0e2135137c71'}}

>>> print(client.secrets.kv.v2.read_configuration(mount_point='secret'))
{'request_id': '747d15c1-9eaa-9ca9-a21b-ac163baf0220', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'cas_required': False, 'max_versions': 0}, 'wrap_info': None, 'warnings': None, 'auth': None}

...and with this: "print(client.secrets.kv.v2.read_secret_version(mount_point='secret',path='pippo/pluto'))" I could read the secret itself, right ?

Thx a lot
