### ISSUE TITLE
TOKEN ROTATION USING PYTHON SCRIPTS

### ISSUE THREAD

**Issue by cave777** [hvac/hvac#404]
Hi, Currently I got an requirement for token rotation. Before expiring our existing token our python script should generate the New secondary token for the account and after 90 days the first token will expires and second token will take the position of first token and gets used for the current policy. Is there any way to automate the token using python scripts.
If yes please provide the sudo code or atlease how to rotate the token. So far I've seen token renewal and token revoke is there any other way so that we can rotate the token by using automation

**Comment by jeffwecan** [comment]
In general, I believe you're after the `Client` class's [`renew_token()` method](https://github.com/hvac/hvac/blob/develop/hvac/v1/__init__.py#L418) but if you can provide specific details around your use case, I could see about adding some explicit examples along those lines to this module's documentation.

**Comment by cave777** [comment]
Actually I did rotate the tokens  using hvac module documentation at first it was difficult to get it but I did it
