### ISSUE TITLE
Ansible fails to read secrets when secrets are in KV2

### ISSUE THREAD

**Issue by c0debreaker** [hvac/hvac#410]
I'm using this code to pull secrets in KV2.

```
prod_db: "{{ lookup('hashi_vault', 'secret=serverlab/production/db token=ce9c4734-4c71-971c-57d7-f5cd7240e860 url=https://127.0.0.1:8200 validate_certs=False')}}"
```

and I tried this too
```
prod_db: "{{ lookup('hashi_vault', 'secret=secret/serverlab/production/db token=ce9c4734-4c71-971c-57d7-f5cd7240e860 url=https://127.0.0.1:8200 validate_certs=False')}}"
```

However, I'm getting this error
```
fatal: [192.168.1.107]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('hashi_vault', 'secret=secret/serverlab/production/db token=ce9c4734-4c71-971c-57d7-f5cd7240e860 url=https://127.0.0.1:8200 validate_certs=False')}}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The secret secret/serverlab/production/db doesn't seem to exist for hashi_vault lookup"}
	to retry, use: --limit @/root/ansible/base.retry
```
the other error is almost exactly the same, the only thing that changed was the secret path in the error message.

I got it to work in KV1
```
prod_db: "{{ lookup('hashi_vault', 'secret=kv-v1/serverlab/production/db token=ce9c4734-4c71-971c-57d7-f5cd7240e860 url=https://127.0.0.1:8200 validate_certs=False')}}"
```

However, it will be painful if we will have to duplicate all our keys. There are values that we don't know too. Is there something I am missing in Ansible that will tell it to use kv2?

I know hvac library can read kv2 since I wrote a python script that imports it. It was able to retrieve the secrets.

**Comment by jeffwecan** [comment]
@c0debreaker: This sort of issue probably makes more sense to file with the ansible side of things at https://github.com/TerryHowe/ansible-modules-hashivault. However I don't mind taking a look when I get some time do so either...

**Comment by c0debreaker** [comment]
It's fixed now. I provided a solution above. :)
