### ISSUE TITLE
Cannot initialize Vault using recovery shares

### ISSUE THREAD

**Issue by derek-pryor** [hvac/hvac#416]
When initializing a Vault deployment configured with a `seal` stanza you are required to specify the `recovery_shares` and `recovery_threshold` values. The current logic make it impossible to initialize Vault in this configuration, as the code path the passes library's the argument checking logic will fail Vault's argument checking logic.

Current argument checking logic: `if recovery_threshold <= recovery_shares:`
Needed argument checking logic: `if recovery_threshold > recovery_shares:`

This logic bug was fixed in f8b7842f but was explicitly reintroduced in e3637383

**Comment by jeffwecan** [comment]
Yup looks like my bad. I'll release a patch version shortly with the correct logic in place asap.

**Comment by derek-pryor** [comment]
Thanks for the quick response
