### ISSUE TITLE
VAULT_ADDR Reference Interfering with Some Workflows

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#421]
Will fill in some thoughts later, just making a placeholder for https://github.com/hvac/hvac/commit/591f6d1fa8601bce4ecd641036c2bb58de22f3e5#r32999249 for now. (cc @mrsiesta)

**Comment by andytumelty** [comment]
FWIW, the functionality implemented in https://github.com/hvac/hvac/pull/411 is the opposite of what the vault cli does.

The behaviour is:
- if no `-address` cli parameter is set, try to use `VAULT_ADDR` environment variable
- if both -address` and `VAULT_ADDR` are set, use the `-address` passed in the vault cli command.

I do feel initialising a client with a specific URL and specific token should always use those values. If they're not set, then yeah, default to the environment variables (but not the other way around!)

**Comment by mrsiesta** [comment]
Thanks for the feedback @andytumelty , I'll get a patch together to more closely follow the standard behaviour.

**Comment by andytumelty** [comment]
Thanks @mrsiesta. FYI I've patched this in a local: https://github.com/andytumelty/hvac/commit/ed85a2746cfeaf5dd02bcd9d07b9f3455c7befa7 -- happy to create a PR if it's helpful (but admittedly I've not put too much thought into the implications of this particular patch!)

**Comment by mrsiesta** [comment]
@andytumelty I had a look at your local change and only had one comment on it. Please create the PR if you have time today, otherwise I'll get a PR going for this later this evening.
