### ISSUE TITLE
tune_mount_configuration and tune_auth_method "options" parameter not recognized

### ISSUE THREAD

**Issue by artis3n** [hvac/hvac#435]
The `tune_mount_configuration` [api docs](https://hvac.readthedocs.io/en/stable/source/hvac_api_system_backend.html#hvac.api.system_backend.Mount.tune_mount_configuration) list a parameter called `options` that "Specifies mount type specific options that are passed to the backend." The [tune_auth_method](https://hvac.readthedocs.io/en/stable/source/hvac_api_system_backend.html#hvac.api.system_backend.Auth.tune_auth_method) does not support this "options" parameter.

I am using this option to configure K8s auth method options. However, when I run the code I get the following error:
`tune_mount_configuration() got an unexpected keyword argument 'options'`. Sure, enough, in the `sys.tune_mount_configuration` function in hvac, no such `options` parameter exists.

I am attempting to create a Kubernetes auth method mount point. The `enable_auth_method` function does not appear to support passing in auth method configuration options, as per [the docs](https://hvac.readthedocs.io/en/stable/source/hvac_api_system_backend.html#hvac.api.system_backend.Auth.enable_auth_method). So I am doing so through the `tune_mount_configuration` function, which does appear to support this capability.

Here is the code. It is called inside of a custom Ansible module:
```python
def write_mount(module_args, client):
    """
    Enables a Vault auth mount point
    :param module_args: AnsibleModule arguments
    :param client: An instantiated hvac.Client
    :return: Status code of the response and the response body as JSON
    """
    try:
        enable_result = client.sys.enable_auth_method(
            path=module_args["mount_point"].capitalize(),
            method_type=module_args["type"],
        )
        tune_result = client.sys.tune_mount_configuration(
            path=module_args["mount_point"].capitalize(),
            options={
                "kubernetes_host": module_args["cluster_hostname"],
                "kubernetes_ca_cert": decode(module_args["cluster_ca_cert"]),
                "token_reviewer_jwt": module_args["cluster_service_token"],
            }
        )

        return {
            "enabled": {
                "status_code": enable_result.status_code,
                "result": enable_result.json(),
            },
            "tuned": {
                "status_code": tune_result.status_code,
                "result": tune_result.json()
            }
        }
    except (TypeError, hvac.exceptions.VaultError) as e:
        raise AnsibleModuleError(results={
            "msg": "Error while enabling and tuning the auth method %s: %s" % (module_args["mount_point"],
                                                                               to_native(e, nonstring='simplerepr'))
        })
```

The `except` clause is triggered with the following result:

```json
{
    "failed": true, 
    "invocation": {
        "module_args": {
            "cluster_ca_cert": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cluster_hostname": "https://127.0.0.1:6443", 
            "cluster_service_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "mount_point": "kubernetes_********3", 
            "state": "present", 
            "type": "kubernetes", 
            "vault_host": "http://127.0.0.1:8200", 
            "vault_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "vault_token": null, 
            "vault_username": "********user"
        }
    }, 
    "msg": "Error while enabling and tuning the auth method kubernetes_********3: tune_mount_configuration() got an unexpected keyword argument 'options'"
}
```

Based on this error, does the `options` parameter not exist for the `tune_mount_configuration` parameter and the documentation is out-of-date? Is there another way through hvac to configure the K8s mount point?

**Comment by artis3n** [comment]
It looks like `enable_secrets_engine()` under sys.mounts includes the `options` parameter. The documentation for `tune_mount_configuration` and `enable_secrets_engine()` should be updated accordingly.

**Comment by artis3n** [comment]
This is all due to the fact that Kubernetes isn't implemented in HVAC yet beyond login.

**Comment by drewmullen** [comment]
```
options={
       "kubernetes_host": module_args["cluster_hostname"],
        "kubernetes_ca_cert": decode(module_args["cluster_ca_cert"]),
        "token_reviewer_jwt": module_args["cluster_service_token"],
}
```

just looking at the docs, i believe the params should be passed to the `config` dict in hvac

**Comment by artis3n** [comment]
> ```
> options={
>        "kubernetes_host": module_args["cluster_hostname"],
>         "kubernetes_ca_cert": decode(module_args["cluster_ca_cert"]),
>         "token_reviewer_jwt": module_args["cluster_service_token"],
> }
> ```
> 
> just looking at the [docs](https://www.vaultproject.io/api/auth/kubernetes/index.html), i believe the params should be passed to the `config` dict in hvac
> 
> i **believe** the only valid value thats ever passed to the `sys/mounts/x/config` `options` key is `version` which is only used on a [kv backend](https://www.vaultproject.io/api/system/mounts.html#options)

The `config` paremeter doesn't allow these values to be passed in - https://hvac.readthedocs.io/en/stable/source/hvac_api_system_backend.html#hvac.api.system_backend.Auth.enable_auth_method

**Comment by drewmullen** [comment]
yeah then thats a problem. we should include `**kwargs`

**Comment by drewmullen** [comment]
@artis3n i believe this will fix your issue... https://github.com/hvac/hvac/pull/461

**Comment by jeffwecan** [comment]
Going to close this issue with the assumption that #461 is sufficient to resolve the concern. Feel free to reopen it if that ends up not being the case! ;)
