### ISSUE TITLE
database secrets engine list_connections error

### ISSUE THREAD

**Issue by drewmullen** [hvac/hvac#454]
regarding: https://github.com/hvac/hvac/pull/431

```
import hvac

def main():
    client = get_client()
    result = client.secrets.database.list_connections()
    print(result)
```
ERROR:
```
Traceback (most recent call last):
  File "db_config.py", line 29, in <module>
    main()
  File "db_config.py", line 10, in main
    result = client.secrets.database.list_connections()
  File "/Users/dmullen/venv/lib/python3.7/site-packages/hvac/api/vault_api_category.py", line 42, in __getattr__
    raise NotImplementedError('"%s" auth method class not currently implemented.')
```

```
$ pip list | grep hvac
hvac                       0.9.1
```

```
$ vault list database/config
Keys
----
test
```

my best guess is that this has to do with `list` possibly not being implemented yet since the error looks similar though im not sure why it mentions `auth method`... will continue to investigate. any thoughts @Dudesons ?
https://github.com/hvac/hvac/blob/9ad27d06658c1e5a8284c7ed02e3c97e8e93ae53/hvac/api/secrets_engines/database.py#L87

https://github.com/hvac/hvac/blob/9ad27d06658c1e5a8284c7ed02e3c97e8e93ae53/hvac/api/vault_api_category.py#L84

**Comment by drewmullen** [comment]
so i noticed that i get the error no matter what function i call in `secrets.database`, even if the function doesnt exist (if its spelled wrong for example). not sure if this is local to my set up or if there's something wrong with how auth methods are called with the module

**Comment by Dudesons** [comment]
@drewmillen I was busy today, I'll try to check that tomorrow

**Comment by drewmullen** [comment]
im pretty sure this has to do with it
https://github.com/hvac/hvac/blob/129d1c036b9107e34fe755ef4e8fa3d919d4f120/hvac/api/secrets_engines/__init__.py#L44

**Comment by drewmullen** [comment]
yep. definitely it. pushing a fix now
