### ISSUE TITLE
docs list deprecated method

### ISSUE THREAD

**Issue by cu** [hvac/hvac#480]
On [this page](https://hvac.readthedocs.io/en/stable/usage/auth_methods/ldap.html), the docs show the method `vault_client.list_auth_backends()`. When calling this in 0.9.2, a DeprecationWarning is printed:

```python
__main__:1: DeprecationWarning: Call to deprecated function 'list_auth_backends'. This method will be removed in version '0.9.0' Please use the 'list_auth_methods' method on the 'hvac.api.system_backend.auth' class moving forward.
```
Obviously the docs are out of date and it's probably a simple fix. However, not being familiar with  the code, I'm stuck on figuring out the right way to call `list_auth_methods`. The obvious thing doesn't work:

```python
>>> client.list_auth_methods()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hvac/v1/__init__.py", line 74, in __getattr__
    deprecated_properties=DEPRECATED_PROPERTIES
  File "/usr/local/lib/python3.7/site-packages/hvac/utils.py", line 137, in getattr_with_deprecated_properties
    item=item,
AttributeError: 'Client' has no attribute 'list_auth_methods'
```

**Comment by drewmullen** [comment]
thanks for pointing that out @cu - try `client.sys.list_auth_methods()` instead

https://hvac.readthedocs.io/en/stable/usage/system_backend/auth.html#id1

**Comment by drewmullen** [comment]
closed by: https://github.com/hvac/hvac/commit/e66cebc7b9f33b7d76644c50961233fb82476c15

sorry for the delay! thanks again for opening
