### ISSUE TITLE
consul.py

### ISSUE THREAD

**Issue by vamshideveloper** [hvac/hvac#496]
Looks like 
https://github.com/hvac/hvac/blob/69e905b9bab2832c5d4bfe10844eca0aea61d6b3/hvac/api/secrets_engines/consul.py#L40
AND
https://github.com/hvac/hvac/blob/69e905b9bab2832c5d4bfe10844eca0aea61d6b3/hvac/api/secrets_engines/consul.py#L90

 .json()  should be removed for above two lines

because while configuring and creating role we do not get any response and it gives error 
*****ValueError: No JSON object could be decoded*****

**Comment by drewmullen** [comment]
im not able to confirm the expected output from the [consul engine documentation](https://www.vaultproject.io/api/secret/consul/index.html) and im not currently using it. however, i'll push a change

**Comment by vamshideveloper** [comment]
When will be these changes reflected in master

**Comment by jeffwecan** [comment]
I'll cut a new release (which implies they changes get pulled into master and published as a new version on PyPi) within the next day or two.
