### ISSUE TITLE
function /sys/wrapping/wrap

### ISSUE THREAD

**Issue by esseti** [hvac/hvac#513]
Is this function not avaliable? https://www.vaultproject.io/api/system/wrapping-wrap.html

if so, why? is it just an implementation choice?

**Comment by jeffwecan** [comment]
Just hasn't been implemented yet! Would welcome contributions along those lines though 😉 

Otherwise, I'll aim to get something added to cover those API routes over the next week or so.

**Comment by esseti** [comment]
I would like to contribute, but I'm stuck at testing the code.
I made the code, I made the test under `tests/integration_tests/api/system_backend/test_wrapping.py`

If I lunch the testing it's `Skipped` any reason?

```
nosetests tests/integration_tests/api/system_backend/test_wrapping.py:TestWrapping

S
----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK (SKIP=1)
```

(many tests are skipped actually)

**Comment by jeffwecan** [comment]
@esseti: Do you have vault installed locally? See:  https://github.com/hvac/hvac/blob/develop/CONTRIBUTING.md#testing

**Comment by esseti** [comment]
apparently the install-vault.sh does not really work on mac, I've installed with brew but now other tests fail. right now I do not have time to test it in deep. 

does anyone have a step-by-step guide on how to contribute on a mac, what env/packages are needed and why the script does not work? `bash: ./vault: cannot execute binary file`
