### ISSUE TITLE
Token Authentication stopped being supported?

### ISSUE THREAD

**Issue by Tylerlhess** [hvac/hvac#520]
OK I upgraded to 9.5 and token auth suddenly became unsupported.
see hvac.api.auth_methods.__init__.py

Token auth is part of the hvac.adapter.Adapter class. It's the default auth method how is it not implemented suddenly? 

I'm going to likely stub out a token auth class to conform to this ridiculous undocumented breaking change to fix it but needing an auth class to support native features seems like a short sight.

**Comment by drewmullen** [comment]
thanks for opening the issue (and the PR!). can you help clarify for me, im not having an issue using tokens. what am i missing?

```
$ pip list | grep hvac
hvac                       0.9.5


>>> client = hvac.Client(url='http://127.0.0.1:8200', token='root')
>>> client.sys.list_mounted_secrets_engines()
{'sys/': {'accessor': 'system_9e53c97c', 'config': {'default_lease_ttl': 0, 'force_no_cache': False, 'max_lease_ttl': 0, 'passthrough_request_headers': ['Accept']}, 'description': 'system endpoints used for contr ...
```

**Comment by Tylerlhess** [comment]
I was getting an unsupported auth method. It is fixed with my pull request #521 

I was trying to use a wrapped token.

like this.

client = hvac.Client(url=VAULT_URL)
client.token = AUTH_TOKEN
if not client.is_authenticated():
    print("Using Cubbyhole auth.")
    logger.info("Using Cubbyhole auth.")

    client.auth_cubbyhole(AUTH_TOKEN)
else:
    print("Using Root Token")
    logger.info("Using Root Token")

**Comment by drewmullen** [comment]
you said this worked for you before? which version of hvac did you upgrade from? would like to try and identify why this broke. 

tbh i havent been using response wrapping, just walked through the [tutorial](https://learn.hashicorp.com/vault/secrets-management/sm-cubbyhole). if i try to apply with HVAC today (0.9.5) heres what works for me

generate a default token to auth
```
VAULT_TOKEN=root vault token create -policy=test -wrap-ttl=1h
...
wrapping_token:                  s.1iUPoIhHl4twQ2bIg81yRskU
```

generate a wrapped token with desired policy
```
VAULT_TOKEN=root vault token create -policy=test -wrap-ttl=1h
Key                              Value
---                              -----
wrapping_token:                  s.tYMhClKWOXMbmhj728fA2OyH
```

use hvac to unwrap
```
>>> import hvac
>>> client = hvac.Client(url='http://127.0.0.1:8200')
>>> client.token = 's.U66tZKARXJ653NKS7MbSlaMN'
>>> client.auth_cubbyhole('s.1iUPoIhHl4twQ2bIg81yRskU')
{'request_id': '732feb0b-dfe2-acd9-eba7-e8c54f7c4782', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': None, 'wrap_info': None, 'warnings': None, 'auth': {'client_token': 's.ZVpHUzRxOX8hRw3DSJkkSonL', 'accessor': 'CExQmVsJxdblgDmVyCaTIMhD', 'policies': ['default', 'test'], 'token_policies': ['default', 'test'], 'metadata': None, 'lease_duration': 2764800, 'renewable': True, 'entity_id': '', 'token_type': 'service', 'orphan': False}
```

the only difference i see between yours and mine is that you're using `AUTH_TOKEN` as both the client token then also attempting to pass it to unwrap.

i guess im mostly trying to understand the behavior you observed and the expected behavior.

**Comment by Tylerlhess** [comment]
Nope I'm an idiot and had rebuild my Vault docker container but not cleared the docker volume. So TL;DR; my auth issues were a failure to auth. 

It lead down to saying Token auth is disabled which it was but it was working in HVAC but when it got down to trying to find an auth that would authenticate it would see I was trying to use Token and that was in the not supported column. Thus generating my error I was seeing but that only happened because the auth wasn't working. So I'll finish out the Token auth class (shouldn't be too hard) so you can just have that done since I'm most of the way done already with it.

But I'm closing this as the issue was really just that token authentication error handling was not implemented. So while I found a bug it was not the one I thought it was.

**Comment by drewmullen** [comment]
thanks man!
