### ISSUE TITLE
Can't parse dictionnary to create_or_update_secret method

### ISSUE THREAD

**Issue by LikoV2** [hvac/hvac#526]
**Briefly describe the issue:**

`vault_co.secrets.kv.v2.create_or_update_secret('prod/' + next(iter(server)), secret=secret)` 
is giving me a 
`json.decoder.JSONDecodeError` 
however 
`vault_co.write('secret/prod/' + next(iter(server)), data=secret)` 
is working fine.

**What did you expect to happen?**

`create_or_update_secret` seems to not validate the dictionnary in the `secret` variable, although  `write` does.

**What did happen?**

`create_or_update_secret` failed.

**Please include helpful code examples so we can attempt to replicate (if applicable):**

Here is the variables:

```
next(iter(server)) = Arthur
secret = {'IP': '192.168.1.4', 'User': 'root', 'Password': 'Pa$$w0rd'}
```
Here is the Stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/hvac/api/secrets_engines/kv_v2.py", line 124, in create_or_update_secret
    return response.json()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This may be not the correct way to create secrets, as the `write` function didn't parse data correctly:
```
$ vault kv get secret/prod/Arthur
==== Data ====
Key     Value
---     -----
data    map[IP:192.168.1.4 Password:Pa$$w0rd User:root]
```
I expected something like:
```
==== Data ====
Key     Value
---     -----
IP    192.168.1.4
Password  Pa$$w0rd
User   root
```
This is maybe related to the `create_or_update_secret` issue, however I can't find the correct way to do it in the documentation.

**Comment by drewmullen** [comment]
hey! you used the proposed template too! thanks

i believe the `write` is deprecated in favor of `create_or_update_secret`

so as far as i can tell, your end goal is just to create a secret with multiple keys, is that correct?

**Comment by drewmullen** [comment]
not sure if i summarized your issue correctly but i did get this to work:

write:
```python
>>> client.secrets.kv.v2.create_or_update_secret(path='test', secret={"key1":1, "key2":2}, mount_point='secret')
{'request_id': 'b294f05e-a2fc-ded3-1597-1999457d2f05', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'created_time': '2019-09-18T16:10:08.8349127Z', 'deletion_time': '', 'destroyed': False, 'version': 1}, 'wrap_info': None, 'warnings': None, 'auth': None}
```

read:
```
>>> client.secrets.kv.v2.read_secret_version(path='test')
{'request_id': 'a1ec005a-95b5-7493-936b-011f44dcd11b', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'data': {'key1': 1, 'key2': 2}, 'metadata': {'created_time': '2019-09-18T16:10:08.8349127Z', 'deletion_time': '', 'destroyed': False, 'version': 1}}, 'wrap_info': None, 'warnings': None, 'auth': None}
```

**Comment by drewmullen** [comment]
check the version of your secret engine `vault secrets list --detailed`

**Comment by LikoV2** [comment]
Hi,

Thanks a lot, that's it, the engine is v1. It's a clean install of Vault so I thought the kv engine defaulted to v2, just like the dev mode server.

From the Vault documentation:
`Additionally, when running a dev-mode server, the v2 kv secrets engine is enabled by default at the path secret/ (for non-dev servers, it is currently v1).`

Thanks again.

**Comment by drewmullen** [comment]
I think it all just depends on the version. I have a 1.2.2 container and that does get kvv2 at `init`

Anyways, glad you got working!
