### ISSUE TITLE
Escape/Quote URL Parameters

### ISSUE THREAD

**Issue by llamasoft** [hvac/hvac#528]
URL placeholders need proper escaping/quoting/encoding to prevent valid names or paths from being misinterpreted.  This is the general case of the related issue #248.

A gist demonstrating the issue can be found here: https://gist.github.com/llamasoft/92f02f7d5b132e9715a2ee8c1f20d5c7

In theory, we should be safe applying `quote(path)` for any field defined as `{path}` and `quote(value, safe="")` for any non-`{path}` fields specified in the [OpenAPI specs](https://www.vaultproject.io/api/system/internal-specs-openapi.html).

- Using `quote(path)` on `{path}`s will prevent characters like `?` or `%` from causing issues while still allowing for `/` to define an actual path location.
- Using `quote(value, safe="")` on non-`{path}` fields will prevent it from being interpreted as anything but a single text value.

**Comment by llamasoft** [comment]
I can work on this issue if that's ok.  I've already started working on a fix that requires minimal changes.

**Comment by jeffwecan** [comment]
@llamasoft Thanks, feel free to submit a PR!
