### ISSUE TITLE
Library should honor environment variable VAULT_CACERT

### ISSUE THREAD

**Issue by Andor** [hvac/hvac#548]
It would be rather cool when the library will be able to read the same configuration as the official vault client.
For now, I want to support [VAULT_CACERT](https://www.vaultproject.io/docs/commands/#vault_cacert) environment variable, which contains the path to file with CA certificate.
It is useful when a self-signed certificate is used 

Maybe it is a good idea to support all of the variables supported by vault client: https://www.vaultproject.io/docs/commands/#environment-variables

**Comment by EvertonSA** [comment]
please can we merge this?
