### ISSUE TITLE
Adapters list function

### ISSUE THREAD

**Issue by Tim1000V** [hvac/hvac#551]
Hi,

I tried to use `secrets.kv.v2.list_secrets` wich use `adapters.list` function. But this function fails with the following error:

`hvac.exceptions.InvalidPath: None`

If I understand your code it calls `session.request` from `requests` module with `'list'` method. 
I'm a little bit confused by this because first of all I wasn't aware of such method for HTTP protocol, and if I turn on the debugger in my web browser, the method used is `'get'`.

Regards

**Comment by Tim1000V** [comment]
Looking further into vault web API you may want to change your code to:
`return self.request('get', url, params={'list': 'true'}, **kwargs)`

**Comment by mikehmbn** [comment]
@Tim1000V I opened the PR https://github.com/hvac/hvac/pull/643 which fixes this issue.
