### ISSUE TITLE
Documentation for EC2 authentication refers to deprecated calls

### ISSUE THREAD

**Issue by pcolmer** [hvac/hvac#554]
https://hvac.readthedocs.io/en/stable/usage/auth_methods/aws.html

The section on EC2 authentication refers to https://hvac.readthedocs.io/en/stable/source/hvac_v1.html#hvac.v1.Client.auth_ec2 which immediately says:

> Call to deprecated function ‘auth_ec2’. This method will be removed in version ‘0.11.2’ Please use the ‘ec2_login’ method on the ‘hvac.api.auth_methods.aws’ class moving forward.

Can the example code please be updated to use ec2_login so that the documentation is best practice?

Thanks.

**Comment by conormancone-cimpress** [comment]
I had this same issue with the IAM auth.  In general it looks like all the documented auth methods have  been deprecated and none of the new auth methods have been documented.  After digging through the auth methods for a while, it's not clear to me how the new auth methods should be used.  Some documentation on these would be very helpful, or perhaps it would be best to wait on deprecating the old ones until the new ones are documented...
