### ISSUE TITLE
Userpass.create_or_update_user() does not allow to specify policies

### ISSUE THREAD

**Issue by stefanlasse** [hvac/hvac#559]
Hi Folks,
according to [here](https://www.vaultproject.io/docs/auth/userpass/#configuration) and [here](https://www.vaultproject.io/api/auth/userpass/index.html#createupdate-user) one must provide a policy for a user to be created in order to receive a token with the respective policy attached.

Using `hvac.api.auth_methods.Userpass.create_or_update_user()` does not allow to specify a policy. How do you do that?

Thanks in advance for the support!

**Comment by jeffwecan** [comment]
My understanding is that if no policies are not specified, the resulting token would simply receive the "default" policy.

> In addition, another built-in policy, default, is created. The default policy is attached to all tokens and provides common permissions.

(quoted from https://www.vaultproject.io/guides/identity/policies/)

**Comment by stefanlasse** [comment]
Yes, that is what i understood, too. But if i want to attach a policy other than the default policy to a freshly baked user, how do i do that? For example with LDAP this is possible (see [here](https://hvac.readthedocs.io/en/stable/source/hvac_api_auth_methods.html#hvac.api.auth_methods.Ldap.create_or_update_user)), for userpass it's not, see [here](https://hvac.readthedocs.io/en/stable/source/hvac_api_auth_methods.html#hvac.api.auth_methods.Userpass.create_or_update_user).

**Comment by vamshideveloper** [comment]
Opened https://github.com/hvac/hvac/pull/562 which can accept policies while creating users
