### ISSUE TITLE
Add request info to exception objects

### ISSUE THREAD

**Issue by and-semakin** [hvac/hvac#579]
Hello!

Sometimes it's difficult to figure out what's wrong with Vault ACL or paths inside of it. It would be very useful if `VaultError` objects contained some information about the request (not only about the response as it is now), for example, at least HTTP method and URL.

Thanks for the library!

**Comment by and-semakin** [comment]
@jeffwecan if you like the idea would you like me to create a PR? I think it won't require a lot of changes.

**Comment by jeffwecan** [comment]
Of course, feel free to give it a go! ☺
