### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'json' on userpass.py

### ISSUE THREAD

**Issue by checor** [hvac/hvac#581]
Hello everyone,

I'm trying this library, and I have to admit that I'm pretty new to it, so maybe I'm doing something wrong.

I want to authenticate to a Vault server using Userpass method.

I created a client without problems, the vault is already unsealed, but I get an error like this:
```
>>> client = hvac.Client(url='MY_SERVER')
>>> client.sys.is_sealed()                                                                                                                                                                                
False 
>>> login_response = client.auth.userpass.login( 
   ...      username="MY_USERNAME", 
   ...      password="MY_PASSWORD"
   ...     ) 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-186fe49f4016> in <module>
----> 1 client.auth.userpass.login(username=username, password=password)

~/.virtualenvs/vualt/lib/python3.6/site-packages/hvac/api/auth_methods/userpass.py in login(self, username, password, mount_point)
    138             json=params,
    139         )
--> 140         return response.json()

AttributeError: 'dict' object has no attribute 'json'
```

Inspecting the file `userpass.py`, I found that some methods are returned like `response.json()`, and others returned like `self._adapter.post( ... )`. I checked other files and most of the returns are like the second one.

Deleting the `.json()` seems to work.

Is a problem in the library or from by side?

Cheers!

**Comment by jeffwecan** [comment]
Howdy @checor! This looks like a bug introduced in the [v0.10.1](https://github.com/hvac/hvac/releases/tag/v0.10.1). I'll try to get a fix merged in and released over the next few days. 

In the meantime, I believe downgrading to v0.10.0 should allow you to work around the issue for now.

**Comment by checor** [comment]
Good to know, thanks.

If I can help in some way, let me know. I think I can write a test to this behavior, but first I need to be able to run the test in my environment 😅

**Comment by horken7** [comment]
I still seem to experience this issue in version 0.10.4.

```
client = hvac.Client(url=server_url, timeout=request_timeout)
resp = self.client.adapter.post("v1/%s" % path, wrap_ttl="1h").json()

---------------------------------------------------------------------------
AttributeError: 'dict' object has no attribute 'json'
```

Has this been tested in version 0.10.4, or is it some issue with my implementation?

**Comment by jeffwecan** [comment]
@horken7: In your example, you should just be able to drop the `json()` call to resolve the issue (while maintaining the previous behavior).

**Comment by horken7** [comment]
@jeffwecan yeah, that works for 0.10.4, but it doesn't seem to be backwards compatible with our previously deployed version (0.9.5). So in this case, I implemented error handling to support both versions. But that works too :)

```
try:
    resp = self.client.adapter.post("v1/%s" % path, wrap_ttl="1h").json()
except AttributeError as e:
    resp = self.client.adapter.post("v1/%s" % path, wrap_ttl="1h")
```

**Comment by jeffwecan** [comment]
Ah yeah that makes sense and I had neglected considering having to support both variations. In general, the `adapter` attribute is not intended to for use by callers external to the module (this is obviously somewhat implicit unfortunately as the attribute is marked as "private" here). Migrating to the more high-level [`client.write()`](https://github.com/hvac/hvac/blob/develop/hvac/v1/__init__.py#L220) method should allow you to avoid that sort of logic I believe.
