### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by and-semakin** [hvac/hvac#582]
I understand that it may be too early to actually drop Python 2 support, because still ~ 40% of downloads come from Python 2 (according to [PyPI stats](https://pypistats.org/packages/hvac)). But it might be a good idea to announce plans in advance and tell users which version of `hvac` will be the latest with Python 2 support. Does the `hvac` project have any plan on this matter?

**Comment by and-semakin** [comment]
Screenshot from PyPI stats to preserve the context:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/9129071/80947485-af974e00-8e09-11ea-81d2-e53b714c8f64.png">

**Comment by jeffwecan** [comment]
Yay, thanks for opening this issue! :D 

I had intended to open something similar soon. My tentative suggestion was going to be something like:

* Split out the current hvac codebase based on Python major version support. 
* `hvac/hvac` (this repo) would only support Python 3.x (and maybe go as far as ending support at Python 3.6 so we can safely use things like f-strings, etc.). 
* Leading up to that point, establish a version with legacy Python support (`hvac/hvac2`) or some such that would be keep up-to-date / maintained on a best-effort sort of basis.
* Start displaying a Python 2.x deprecation notice within the module pointing people towards the legacy package.
* Drop Python 2.x support after N number of releases with the deprecation notice in place.


Alternatively, we could just say "after release X, hvac will not provide Python 2.x support in any form, so X is the last available release for those versions".

**Comment by and-semakin** [comment]
Pallets Project (`flask`, `werkzeug`, `jinja2`) decided just to bump a major version to indicate this breaking change. Python 2 users won't be able to install the latest version, but `pip` will install the latest version with Python 2 support for them. I think it's a good approach.

See their blog: https://palletsprojects.com/blog/ending-python2-support/

**Comment by jeffwecan** [comment]
Ever so slightly started down this route by dropping Python 2.7 from our test matrix. Mainly because it was making implementing https://github.com/hvac/hvac/pull/666 more complicated than desired.

**Comment by briantist** [comment]
@jeffwecan as a maintainer for a project that depends on `hvac`, I would love to get an idea on when/how py2 support will be officially dropped, following up #706 .

Even if a date is not possible, an expected version number would be great. I personally would prefer a new major version for that although it is less clear with `hvac` still being in zero-ver. But even knowing that for example, `0.11.0` or `0.12.0` will drop it is helpful in pre-emptively setting up version constraints and allowing downstream projects to prepare documentation and communication.

Thanks for all your work on `hvac`!

**Comment by jeffwecan** [comment]
@briantist: Our tentative plans are to make the next release a major version bump and for that `1.0.0` release to mostly be restricted to the changes involved in dropping Python 2.7 support. And thus, also finally get us graduated from zero-ver 😂! (Though fair warning, I've also been considering if [CalVer](https://calver.org/) might be a better fit for how hvac is maintained...). I'm _hoping_ to have enough time between now and the stated release date (2021/07/01) for https://github.com/hvac/hvac/milestone/3 to get it shipped by then.

If it would help to have a more deliberate discussions around the implications of this change or the like, please just let me know!

**Comment by briantist** [comment]
Thank you Jeff, that's helpful, as the expected release date gets closer and decisions around versioning, breaking changes, etc. are solidified, updates posted here (or somewhere?) are much appreciated!

**Comment by briantist** [comment]
One other thing that would be helpful to know, is which versions of Python 3 are expected to remain supported and tested against, and whether there's a place to track that.

**Comment by jeffwecan** [comment]
@briantist: Apologies for the delay in responding back to ya, other obligations have kept me from making too much headway on this front. However, I'm hoping to have some time over the next week or so to get it wrapped up!

>  as the expected release date gets closer and decisions around versioning, breaking changes, etc. are solidified, updates posted here (or somewhere I can follow/subscribe to) are much appreciated!

I'll share some more along the lines this weekend (🤞🏻 ) after I work through some of the associated implications in earnest. The (updated) tentative release date for hvac 1.0 / dropping Python 2.x support is now: Monday July 19th, 2021. I'm hoping a concerted effort, over the next week, to announce the pending major version bump and Python support changes will give interested folks with a hvac dependency at least a decent chance of receiving a heads-up beforehand.

> One other thing that would be helpful to know, is which versions of Python 3 are expected to remain supported and tested against, and whether there's a place to track that.

On the first point, we'll be moving to a min supported Python version of >=3.6 here (barring some large contingent of users making a compelling case for support of earlier 3.x versions as well...).

I'll update our README with the specifics but otherwise I expect our [setuptools (setup.py)](https://github.com/hvac/hvac/blob/develop/setup.py) to be the canonical source of that info. I.e., I'll include a [`python_requires` argument](https://packaging.python.org/guides/dropping-older-python-versions/#specify-the-version-ranges-for-supported-python-distributions) there as part of the upcoming changes.

**Comment by briantist** [comment]
Got it, thanks @jeffwecan , I will look at a likely announcement for dropping of Py3.5 support in `community.hashi_vault` v2 as well then.

**Comment by and-semakin** [comment]
For historical purposes, here's how the picture of 2 vs 3 among `hvac` users looks in the last 6 months:

![image](https://user-images.githubusercontent.com/9129071/125030224-30a04400-e0a4-11eb-86bb-029fc3cd3e91.png)

**Comment by jeffwecan** [comment]
So a slight tweak to [my stated plans](https://github.com/hvac/hvac/issues/582#issuecomment-876615412) from last week:

There will be one minor release (`0.11`) made shortly that will (ideally) be the last release before we explicitly dropped Python 2.7 support with version `1.0`'s release next week. The primary motivation for this is to have a published release with `python_requires='>=2.7'` _before_ we update it to `>=3.6` (as I'm given to understand thats required for pip's automatic fallback). 

That said, I'm expecting this `v1` branch to cover most all that changes intended to go out with our 1.0 release in case anyone would like to reference it in the meantime: https://github.com/hvac/hvac/pull/729

**Comment by jeffwecan** [comment]
Oh! and also worth calling out that I intend to clear out all the methods marked as "deprecated" in the primary "`hvac.Client`"  class as part of the v1 release (barring any reasonable objections there). It would be nice to avoid overloading those changes with the drop of Python 2.7 support but I'd like to batch them together for expediency's sake. I'll include a relatively detailed migration guide for these methods in the v1 changelog entries as well (I'll aim to merge those bits into develop over the next few days).

**Comment by pgajdos** [comment]
Could you please also consider to drop mock usage in favor of unittest.mock?
