### ISSUE TITLE
Minor release please

### ISSUE THREAD

**Issue by jschlyter** [hvac/hvac#588]
Would it be possible to create a minor release fixing #584 ? Without it Transit does not work JWS. If a normal release is schedule for this week, this request can be ignored.

**Comment by jeffwecan** [comment]
Sure thing! Sorry I've been a bit busy with other tasks as of late. I'll aim to put out a release sometime over the next few hours @jschlyter.

**Comment by jonathanunderwood** [comment]
Think this can be closed.
