### ISSUE TITLE
Ensure Docstrings Specify Correct Return Type Following #537

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#604]
> Okay, this one was really confusing, because the documentation, which really copies doctstrings from the source code, still says to expect requests responses instead of the JSON body for non-204 responses. Should we update the docstrings?

https://github.com/hvac/hvac/pull/537#issuecomment-660304707

**Comment by trishankatdatadog** [comment]
Thanks for filing this issue, Jeff!

Another thing to note: the doctstrings don't mention P-384 and RSA-3072, even though both seem to be supported by Vault itself...

Let me see what I can do to help 🙂 Should we divvy up tasks?
