### ISSUE TITLE
Auth with OIDC

### ISSUE THREAD

**Issue by SimonGurney** [hvac/hvac#607]
Is it possible to implement OIDC auth in this library?

https://www.vaultproject.io/docs/auth/jwt_oidc_providers

**Comment by jeffwecan** [comment]
It is possible one way or another but not with first-class support / documentation at the moment. I'll look at including expanded support of OIDC along those lines in our next release however. 👍

**Comment by jeffwecan** [comment]
This has been added and the documentation is up at: https://hvac.readthedocs.io/en/stable/usage/auth_methods/jwt-oidc.html

Let me know if you have any questions, etc. ☺

**Comment by gh-amaroo** [comment]
Hi, @jeffwecan  thank you so much for the document update. Wanted to request if you could add example code which would correspond to CLI command `vault login -method=oidc --role=<role-name>`.
in current documents its unclear to me. 
thank you.

**Comment by jeffwecan** [comment]
@gh-amaroo: https://hvac.readthedocs.io/en/stable/usage/auth_methods/jwt-oidc.html#oidc-authorization-url-request would cover the equivalent functionality as your example CLI command. I'll see about adding some context around that example to make things a bit more clear. (I like the idea generally of including the equivalent CLI commands next to hvac examples to make translating between the two easier 🤔.)

**Comment by teixeiralari** [comment]
Hi @jeffwecan, you mentioned above that this method (https://hvac.readthedocs.io/en/stable/usage/auth_methods/jwt-oidc.html#oidc-authorization-url-request ) would be equivalent to this command:  `vault login -method=oidc`.
I tried to use this method, but it's been hard for me to understand how to use it. Could you please provide an example on how to use it? I really appreciate your support. Thank you.

**Comment by jeffwecan** [comment]
@teixeiralari https://github.com/hvac/hvac/pull/638 ostensibly includes a working example. Which is presumably implicated in #678. I'll confirm here after I start work on #678 (hopefully a bit later today).

**Comment by jeffwecan** [comment]
^ That was indeed the case. Long story short, there is a more detailed example for `oidc_authorization_url_request` reflected in the stable / default version of the documentation at https://hvac.readthedocs.io/en/stable/usage/auth_methods/jwt-oidc.html#oidc-authorization-url-request (In the short term, you may need to clear your local browser cache if you're seeing something other than `Revision e2fe2f00` in the footer.)
