### ISSUE TITLE
Support for Google IAP 

### ISSUE THREAD

**Issue by Borg-Can-Code** [hvac/hvac#620]
Hello, I am unable to find support for Google IAP in this package. 

Is there any plans to support Google IAP in the near future?

**Comment by jeffwecan** [comment]
Which Vault auth method and/or secrets engine in particular are you looking to use with Google IAP?

**Comment by Borg-Can-Code** [comment]
We secure our vault instance behind IAP so when I send my login request via client.auth.gcp.login() the request MUST contain the authorization header or it is denied by the proxy prior to hitting the vault instance.

`  File "C:\Development\Python\us-cert\venv\lib\site-packages\hvac\adapters.py", line 347, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "C:\Development\Python\us-cert\venv\lib\site-packages\hvac\adapters.py", line 309, in request
    utils.raise_for_error(
  File "C:\Development\Python\us-cert\venv\lib\site-packages\hvac\utils.py", line 39, in raise_for_error
    raise exceptions.Unauthorized(message, errors=errors, method=method, url=url)
hvac.exceptions.Unauthorized: Invalid IAP credentials: empty token, on post https://myco.company.com/v1/auth/gcp/login`


To test I added the bearer auth into the authorization header and we have lift off.

From hvac/adapters.py
Added this this at line 281
`        if bool(re.match('.*myco.*', url)):
            iap_token = 'validJWT'
            headers['Authorization'] = f'Bearer {iap_token}'

        wrap_ttl = kwargs.pop('wrap_ttl', None)
        if wrap_ttl:
            headers['X-Vault-Wrap-TTL'] = str(wrap_ttl)

        _kwargs = self._kwargs.copy()
        _kwargs.update(kwargs)

        response = self.session.request(
            method=method,
            url=url,
            headers=headers,
            allow_redirects=self.allow_redirects,
            **_kwargs
        )`
An example of this can be shown here - https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iap/make_iap_request.py

Output from the following login


`        if self.client.is_authenticated():
            print("successfully authenticated to vault")
        else:
            print("failed to authenticate to vault")


        jwt = self.generate_jwt().decode("utf-8")
        self.client.auth.gcp.login(
            role='my-role',
            jwt=self.generate_jwt().decode("utf-8"),
            # namespace='my-namespace'

        )
        if self.client.is_authenticated():
            print(f"successfully authenticated to vault: {self.VAULT_URL}")
        else:
            print("failed to authenticate to vault")`


failed to authenticate to vault
successfully authenticated to vault: https://myco.company.com

**Comment by Borg-Can-Code** [comment]
I wrote a module to support this functionality and would like to work with the project maintainers to get this in the official code base if possible.

https://github.com/hvac/hvac/pull/621

**Comment by jeffwecan** [comment]
@Borg-Can-Code: That PR looks great! I'll try to get it reviewed and/or merged in some time this week.

**Comment by Borg-Can-Code** [comment]
Thanks @jeffwecan!

Please let me know if there is anything adjustments that need to be made to this code to in order to get this change merged. I look forward to your review!

**Comment by jeffwecan** [comment]
Frankly, the only thing that has kept me from merging it in already is finding the time needed to read + understand how this new adapter would be leveraged and then writing up some documentation to cover it. If you're willing to have a go at adding some documentation (I figure it could be added under a new subheading here: https://github.com/hvac/hvac/blob/develop/docs/advanced_usage.rst#custom-requests--http-adapter ) that would be a big help. ☺

**Comment by Borg-Can-Code** [comment]
As per your comments I added some documentation on functionality, usage and how to create your own AdvancedProxy plugin.

**Comment by jeffwecan** [comment]
Thanks so much @Borg-Can-Code! I should have some time over the next day or so and will look at merging in the proposed PR + cutting a release as I'm able. 👍
