### ISSUE TITLE
[question] permission denied but working with vault login command

### ISSUE THREAD

**Issue by u007** [hvac/hvac#630]
ive created a new policy and set "read", "list" permission to a path,
then im using kv2 and set the path and set the json value.
ive generated token with the new policy.

its working both locally on the same machine and also on the machine that hosted my python application using "vault" cli with the generated token of the new policy.

but when i use hvac in python to retrieve it, i get permission denied

```
hvaultClient = hvac.Client(url=HVAULTURL)
hvaultClient.token = os.environ['VAULT_TOKEN']
hvaultClient.is_authenticated()# this return true, and false if my token is invalid
vaultResponse = hvaultClient.secrets.kv.v2.read_secret_version(path='nn/my-path') # permission denid
```

my policy:
```
path "auth/token/lookup-self" {
  capabilities = ["read"]
}

# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}

# Allow tokens to revoke themselves
path "auth/token/revoke-self" {
    capabilities = ["update"]
}

# Allow a token to look up its own capabilities on a path
path "sys/capabilities-self" {
    capabilities = ["update"]
}

# Allow a token to look up its own entity by id or name
path "identity/entity/id/{{identity.entity.id}}" {
  capabilities = ["read"]
}
path "identity/entity/name/{{identity.entity.name}}" {
  capabilities = ["read"]
}


# Allow a token to look up its resultant ACL from all policies. This is useful
# for UIs. It is an internal path because the format may change at any time
# based on how the internal ACL features and capabilities change.
path "sys/internal/ui/resultant-acl" {
    capabilities = ["read"]
}

# Allow a token to renew a lease via lease_id in the request body; old path for
# old clients, new path for newer
path "sys/renew" {
    capabilities = ["update"]
}
path "sys/leases/renew" {
    capabilities = ["update"]
}

# Allow looking up lease properties. This requires knowing the lease ID ahead
# of time and does not divulge any sensitive information.
path "sys/leases/lookup" {
    capabilities = ["update"]
}

# Allow a token to manage its own cubbyhole
path "secrets/*" {
    capabilities = ["read", "list","create","update", "delete"]
}
path "nn/*" {
    capabilities = ["read", "list"]
}

# Allow a token to wrap arbitrary values in a response-wrapping token
path "sys/wrapping/wrap" {
    capabilities = ["update"]
}

# Allow a token to look up the creation time and TTL of a given
# response-wrapping token
path "sys/wrapping/lookup" {
    capabilities = ["update"]
}

# Allow a token to unwrap a response-wrapping token. This is a convenience to
# avoid client token swapping since this is also part of the response wrapping
# policy.
path "sys/wrapping/unwrap" {
    capabilities = ["update"]
}

# Allow general purpose tools
path "sys/tools/hash" {
    capabilities = ["update"]
}
path "sys/tools/hash/*" {
    capabilities = ["update"]
}

# Allow checking the status of a Control Group request if the user has the
# accessor
path "sys/control-group/request" {
    capabilities = ["update"]
}

```

os: ubuntu 18.04
Python 3.6.9

**Comment by jeffwecan** [comment]
If I'm following correctly, it looks like changing the `hvaultClient.secrets.kv.v2.read_secret_version(path='nn/my-path')` call to this instead would resolve things:

```
vaultResponse = hvaultClient.secrets.kv.v2.read_secret_version(path='my-path', mount_point='nn')
```

Reference: https://hvac.readthedocs.io/en/stable/source/hvac_api_secrets_engines.html#hvac.api.secrets_engines.KvV2.read_secret_version

I'll grant that having both a `path` and `mount_path` parameter on such methods is more confusing than intended in many cases. Ideally we'll be able to refactor things in the future to make things clearer but using `mount_point` in the meantime will hopefully resolve your issue.

**Comment by akamensky** [comment]
Seeing the same on latest vault/hvac versions. Does anyone bother to fix this? This is obviously not how it should work. `kv.read_secret(path='mp/secret')` gets me `permission denied`, but `kv.v2.read_secret(path='secret', mount_point='mp')` works?

**Comment by ohcnkk** [comment]
Adding `mount_point` works for me.

**Comment by briantist** [comment]
This looks solved to me, I would encourage anyone having a new issue to open a new [Q&A Discussion](https://github.com/hvac/hvac/discussions/categories/q-a).

**Comment by mababio** [comment]
I tried above solution, but it didn't resolve my issue. I had to mention the namespace in the Client method as well.

**Comment by briantist** [comment]
Hi @mababio , that seems right to me, if you are using a namespace, you should initialize the client with it: https://hvac.readthedocs.io/en/stable/overview.html#initialize-the-client

If you'd like to dig into or troubleshoot further please open a [Q&A discussion](https://github.com/hvac/hvac/discussions/categories/q-a), thanks!
