### ISSUE TITLE
JWT login doesn't set the token automatically

### ISSUE THREAD

**Issue by briantist** [hvac/hvac#644]
I'm not the most familiar with this codebase so bear with me and sorry if I'm misunderstanding something.

When using the `jwt_login` method, the resulting token is not automatically set in the client in the way it is with other auth methods.

I believe the reason is that it uses the `post` adapter rather than the `login` adapter used by other auth methods, as it seems the token being put into the client is done there.

`jwt_login`: https://github.com/hvac/hvac/blob/develop/hvac/api/auth_methods/jwt.py#L403-L406

`ldap_login` (for reference): https://github.com/hvac/hvac/blob/develop/hvac/api/auth_methods/ldap.py#L377-L381

the `login` adapter: https://github.com/hvac/hvac/blob/9e5fc7036e05b3a77f10e9d2f12438b8250d1609/hvac/adapters.py#L161-L183

The tests for JWT seem to acknowledge this difference, as they manually set the token: https://github.com/hvac/hvac/blob/develop/tests/integration_tests/api/auth_methods/test_jwt.py#L262

---

If JWT auth can't use the `login` adapter for some reason, maybe it should include its own code to set the token in the client.
At worst, if that can't be done, then the documentation and examples should make this clear, so that clients can adapt.

**Comment by briantist** [comment]
Hi @jeffwecan sorry to ping is there a better way to draw attention to issues, any particular channel or process to follow?

**Comment by jeffwecan** [comment]
Howdy @briantist! No worries; especially as an `@` on GitHub is probably the best way to get my attention at the moment. :) 

Regarding the issue, I believe the use of `post` over `login` on its adapter instance is just an oversight. I'll attempt to find some time to look at correcting the matter in the near future.

**Comment by briantist** [comment]
Sounds good, thanks for taking a look!

**Comment by briantist** [comment]
Just saw this, related: https://github.com/hvac/hvac/pull/637#issuecomment-719576036

**Comment by odeshog** [comment]
@jeffwecan the userpass auth back also uses post instead of login.
