### ISSUE TITLE
requirements.txt strictness incompatible with pip 20.3

### ISSUE THREAD

**Issue by sodul** [hvac/hvac#652]
We depend on other package than hvac which strictly require different versions of the dependencies. This is now causing installation failures with pip 20.3:
https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The dependency requirements need to be relaxed in order for hvac to be installed.

**Comment by MisguidedEmails** [comment]
It doesn't look like the `requirements.txt` is taken into account when the package is installed by looking at the [setup.py](https://github.com/hvac/hvac/blob/9f29cad81b2fa3685030dff77b0d7f7642650368/setup.py#L31-L34), and when viewing the dependancy tree with [pipdeptree](https://github.com/naiquevin/pipdeptree). The package requires `requests>=2.21.0` as stated in the `setup.py` file which was released around 2 years ago.

**Comment by sodul** [comment]
I can confirm we were able to upgrade to Python 3.9.1 and Pip 20.3.3 recently. We are still on hvac 0.10.5 and there was no issue with that version.

That said we use pip with `--use-deprecated=legacy-resolver` as a workaround since several other packages we use have strict versions.

**Comment by uranusjr** [comment]
Hi, I’m a maintainer of pip and worked on the depenency resolver. It seems like I can install the latest hvac version (0.10.9) correctly. Is this still an issue, or is there context I’m missing?

**Comment by briantist** [comment]
As far as I know this should not be an issue anymore, as we've bumped up some dependencies since this was opened. We're also bumping more dependencies for the upcoming `v2.0.0` release now that we're dropping Python 3.6 & 3.7, since supporting 3.6 was preventing us from using modern versions of some of the dependencies:
- #1048

**Comment by sodul** [comment]
We are now on hvac 1.2.1 (latest) and pip 23.2.1. This is no longer an issue.
