### ISSUE TITLE
is this still valid for auth_approle?

### ISSUE THREAD

**Issue by eduda** [hvac/hvac#658]
https://hvac.readthedocs.io/en/stable/usage/auth_methods/approle.html#authentication
appears to be deprecated? if so, do you have an example of new approle login?

**Comment by jeffwecan** [comment]
@eduda: Yes that snippet of documentation is indeed out of date. We'll look at getting it updated with the newer approle methods but in the meantime hopefully trying something like this will get you on the right track (assuming you have an approle auth method mounted on the default `approle/` path):

```python
client.auth.approle.login(
    role_id='<some_role_id>',
    secret_id='<some_secret_id>',
)
```

**Comment by eduda** [comment]
thanks for the example. works.

**Comment by StanfordLin** [comment]
Please update! Spent a couple hours only to find out it was a documentation error, pretty new to hvac, thanks!
