### ISSUE TITLE
Potentially misleading requirements.txt

### ISSUE THREAD

**Issue by MisguidedEmails** [hvac/hvac#659]
I was curious what the `requirements.txt` file is used for in this repo? I assumed it was the requirements for the package itself, however it's not used at all when installing the package, as that information is in `setup.py` (and isn't configured to read from `requirements.txt`). It looks like it's used for CI/Tox, but I'm not sure why that's used over getting Tox to install dependancies via `setup.py`.

Could anyone shed light on this? I'm asking as it can be a bit misleading having two sets of requirements in the repo.

**Comment by jeffwecan** [comment]
@MisguidedEmails: No particular reason to have them defined in both locations, just a vagrancy of some of the initial maintainers' arrangements. As is I would break it down like this:

- `requirements.txt` -> `pip-compile`'d version of the base requirements used during CI runs and the like. I.e., list of explicit module versions used during development / CI.
- `setup.py` minimal requirements without pinning them to a single version

My thinking on the matter aligns pretty well with this StackOverflow contributor's: 

> Do I really need both?
> 
> Short answer is no, but it's nice to have both. They achieve different purposes, but they can both be used to list your dependencies.

(via: https://stackoverflow.com/a/49684835).

PRs of course very welcomed if you would like to propose changes on this front. 😄

**Comment by jeffwecan** [comment]
Ah, and now I just saw https://github.com/hvac/hvac/issues/652 which documents a compelling reason that having the two sources documenting requirements maintained independently is a Bad Idea heh.

**Comment by briantist** [comment]
We've since moved to poetry in #854 and things should be clearer now with `pyproject.toml`:
- https://github.com/hvac/hvac/blob/main/pyproject.toml
