### ISSUE TITLE
readthedocs master and stable are out of date with v0.10.8

### ISSUE THREAD

**Issue by ap0ught** [hvac/hvac#678]
I came to the site because of a depreciation error and I did not see an updated version or the call on this [page](https://hvac.readthedocs.io/en/stable/usage/auth_methods/approle.html)

or [this page](https://hvac.readthedocs.io/en/master/usage/auth_methods/approle.html)

After some digging I noticed that master had been renamed to main so the "master" branch has been left at the v0.10.6 branch.  It seems to not be bringing in the main branch. 

[0.10.6 (December 14th, 2020)]( https://hvac.readthedocs.io/en/master/changelog.html ) 
 [0.10.6 (December 14th, 2020) ](https://hvac.readthedocs.io/en/stable/changelog.html )
[ 0.10.8 (February 8th, 2021) ]( https://hvac.readthedocs.io/en/latest/changelog.html )
[ 0.10.8 (February 8th, 2021) ]( https://hvac.readthedocs.io/en/v0.10.8/changelog.html )

**Comment by jeffwecan** [comment]
Thanks so much for pointing this issue out @ap0ught! You were indeed correct, I had neglected to enable builds of the `main` branch with hvac's readthedoc.io settings after performing that rename. This has now been remedy and the stable version of the docs has been rebuilt:

```shellsession
%▶ git rev-parse --short main
e2fe2f0
%▶ git rev-parse --short v0.10.8
e2fe2f0
%▶ lynx --dump https://hvac.readthedocs.io/en/stable/index.html | ggrep -oP '(?<=Revision ).*(?=\.)'
e2fe2f00
```

I'll go ahead and close out this issue but please do let me know if you encounter anything astray 😄
