### ISSUE TITLE
How to read secret in hvac v2?

### ISSUE THREAD

**Issue by Vox1984** [hvac/hvac#682]
Hello Guys,

I was happily reading secrets from Vault (auth via kubernetes) with version v1.

I was using:
dictResponse = client.kv.v1.read_secret(mount_point='dev', path='pass')

How do I migrate this simple code to version v2?
https://hvac.readthedocs.io/en/stable/usage/secrets_engines/kv_v2.html#

There is no such section about reading secret in the documentation and `client.kv.v2.read_secret` does not work giving error:
`AttributeError: 'KvV2' object has no attribute 'read_secret'`

I am a bit confused here... All the v2 documentation is about versions, configs, but nothing about such a simple thing as reading secrets... Please help me out

**Comment by mblau-leaffilter** [comment]
Hello Vox,

I had noticed that myself and have submitted a pull request that adds the missing read_secret function to kv_v2

**Comment by sshishov** [comment]
The issue will be fixed by PR #686

**Comment by Vox1984** [comment]
very nice :+1:

**Comment by mblau-leaffilter** [comment]
@Vox1984 this has been included in the latest release.

**Comment by briantist** [comment]
Added in #686
