### ISSUE TITLE
No Option to Set "delete-version-after" for a Secret in KV-2

### ISSUE THREAD

**Issue by yks0000** [hvac/hvac#693]
Please help know how to set delete-version-after in using KV-2 Python hvac.

**Comment by jeffwecan** [comment]
I'll see about getting #694 out in a release sometime over the next week or so. If there is anything beyond that we can look at for resolving this issue, please just let us know @yks0000!

**Comment by yks0000** [comment]
@jeffwecan Thank you. I will wait for release.
