### ISSUE TITLE
0.10.13 release still doesn't work in Python 2

### ISSUE THREAD

**Issue by briantist** [hvac/hvac#711]
Related: #706 

@jeffwecan I'm still seeing an issue with on the newly added line:
https://github.com/hvac/hvac/pull/708/files#diff-f777c30249cbcd87c4079dcfde653e10a53132909851c7f1bdd976a8df34e9daR254

It seems the comma at the end is causing a failure in Python 2.7, example from my CI with 0.10.13:
https://github.com/ansible-collections/community.hashi_vault/runs/2633863806?check_suite_focus=true#step:5:568

See also: https://stackoverflow.com/q/16950394/3905079

**Comment by jeffwecan** [comment]
Ah shucks, I noticed that at some point and forgot to push up a commit correcting it for the implicated release. Will ship another patch here as soon as I can.
