### ISSUE TITLE
Does auth.token.create support orphan tokens?

### ISSUE THREAD

**Issue by thehilll** [hvac/hvac#758]
We are receiving this deprecation warning when calling `create_token`:

```
DeprecationWarning: Call to deprecated function 'create_token'. This method will be removed in version '1.0.0' Please use the 'create' method on the 'hvac.api.auth_methods.token' class moving forward.
```

However, we are creating these tokens as orphans by setting `orphan=True` when calling `create_token`.  Also, the client that creates the tokens is authenticated with sudo privileges, not a root token.

In looking at the new method `auth.token.create` there is no `orphan` argument, but there is a `no_parent` one which is passed as a parameter to the API endpoint.

However, to create an orphan token via sudo privileges the endpoint used must be `/auth/token/create-orphan`:

> If used via the /auth/token/create-orphan endpoint, a root token is not required to create an orphan token (otherwise set with the no_parent option).

In the deprecated `Client.create_token` method if the `orphan=True` argument is passed it uses the `create-orphan` endpoint:

```
if orphan:
    return self._adapter.post(
        "/v1/auth/token/create-orphan", json=params, wrap_ttl=wrap_ttl
    )
```

In the new `auth.token.create` method there appears to be no way to call the `create-orphan` endpoint.  It is always the `create` one.  It appears this could be similarly handled by adapting the endpoint based on the `no_parent` argument, something like:

```
if no_parent:
    create_endpoint = 'create-orphan'
else:
    create_endpoint = 'create'

if role_name is not None:
    api_path = "/v1/auth/{mount_point}/{create_endpoint}/{role_name}".format(
        mount_point=mount_point,
        create_endpoint=create_endpoint,
        role_name=role_name,
    )
    return self._adapter.post(
        url=api_path,
        json=params,
    )

api_path = "/v1/auth/{mount_point}/{create_endpoint}".format(
    mount_point=mount_point,
    create_endpoint=create_endpoint
)
return self._adapter.post(
    url=api_path,
    json=params,
    wrap_ttl=wrap_ttl,
)
```

Maybe I'm missing something and there is already a way to access the `create-orphan` endpoint using non-deprecated paths, but if not is this a good way to handle it?  If so we could test and submit a pull request.

Thanks.

**Comment by briantist** [comment]
I would like to second this request. It does indeed seem like the new method can only create orphans through the `/create` endpoint which requires a root token, so we will be losing functionality if the old method is deprecated without a replacement.

@jeffwecan with 1.0.0 being the next expected version, is there any place to track things like that this that ought to be addressed beforehand, to ensure removed deprecated methods have replacements?

**Comment by briantist** [comment]
Re: the implementation suggested, I wonder if there's value in re-implementing the `orphan` parameter, which seemed to work in conjunction with `no_parent`; the idea being that `no_parent` could be used with either the `/create` or `/create-orphan` endpoint, and the setting of `orphan` determines which endpoint to call.

I cannot tell from the Vault documentation whether there would ever be value in calling the `/create` endpoint over the `/create-orphan` endpoint though (when the intention is to create an orphan). The value of `/create-orphan` is that it can work without a root token, but if you have a root token, I'm not sure there's any point is insisting to use `/create`, if that makes sense.

So I may be wrong on that.

**Comment by briantist** [comment]
> I would like to second this request. It does indeed seem like the new method can only create orphans through the `/create` endpoint which requires a root token, so we will be losing functionality if the old method is deprecated without a replacement.
> 
> with 1.0.0 being the next expected version, is there any place to track things like that this that ought to be addressed beforehand, to ensure removed deprecated methods have replacements?

@colin-pm just wanted to ask about this again, with 1.0.0 coming up; both the issue at hand and whether there's a place to track any other things that are slated to be removed but don't have replacements

**Comment by colin-pm** [comment]
I created a separate Token method that creates an orphaned token in #869. This should give HVAC users the ability to either use the `create` method with `no_parent` or use the `create_orphan` method. Which method the user shall choose will depend on their unique situation, if they are using a root token, or have permission to use the create_orphan API endpoint.

@thehilll Let me know if this proposed change satisfies your use case.

**Comment by thehilll** [comment]
Yes, it does.  Thank you very much.
