### ISSUE TITLE
v0.11.1 won't load, six is no longer in setup.py but is used in utils.py

### ISSUE THREAD

**Issue by targetdrone** [hvac/hvac#765]
Release v0.11.1 commit c9ff353 is labeled "Drop six from requirements" and removed six from requirements-dev.txt, requirements.in, requirements.txt, and setup.py.  However, [line 11 in hvac/utils.py](https://github.com/hvac/hvac/blob/0e78da45711f6d30e924e95a38e456c5fd104eec/hvac/utils.py#L11)  still calls `import six`, causing hvac to fail to load.

**Comment by targetdrone** [comment]
Actually six is still referenced down in lines 360-362, so this isn't a complete fix for the code.

**Comment by bobmshannon** [comment]
This should be fixed by https://github.com/hvac/hvac/pull/768.

**Comment by briantist** [comment]
Yes, fixed by #768
