### ISSUE TITLE
Stale python-jwt requirement?

### ISSUE THREAD

**Issue by mgorny** [hvac/hvac#766]
`requirements-dev.in` states that `python_jwt` is a requirement for this package. However, I can't find a single import of it in the source code and FWICS tests pass fine without it. Is the dependency obsolete?

**Comment by briantist** [comment]
Hi @mgorny , thanks for raising this. It's still there in our dev requirements and I also cannot find any reason it needs to be. I would have guessed it might have been used in tests for one of the methods that use JWTs like JWT/OIDC auth, or the Azure auth method but I don't see anything.

I'm going to look to remove this requirement and see what breaks.

In any case it was never a requirement for using `hvac`.
