### ISSUE TITLE
approle generate_secret_id(): metadata are always provided, even if empty

### ISSUE THREAD

**Issue by Prividen** [hvac/hvac#781]
Function generate_secret_id is always include metadata in Vault request, even it is empty.

Code like this:
```
secret_request = client.auth.approle.generate_secret_id(
    role_name=role_name,
)
```

produce the following request to Vault:
```json
{ "request": {
...
    "data": {
      "metadata": null
    },
...
}
```

Usually it has no any side effect, unless you have restriction policy with the only allowed parameters, not included the ```metadata``` itself:
```hcl
path "auth/approle/role/client-role-*" {
  capabilities = ["create", "update"]
  allowed_parameters = {
    "token_policies" = ["client-policy"]
    "token_ttl" = ["30s"]
    "token_max_ttl" = ["1h"]
  }
}
```

Then you always got exception:
```
hvac.exceptions.Forbidden: 1 error occurred:
	* permission denied

, on post https://my.vault.org/v1/auth/approle/role/client-role-1/secret-id
```

The fix is easy - do not provide ```metadata``` parameter, if it empty.

**Comment by nafziger** [comment]
I've had this same issue and come to the same conclusion.
