### ISSUE TITLE
OIDC Authorization Example Issue

### ISSUE THREAD

**Issue by Woovie** [hvac/hvac#788]
On the [JWT/OIDC documentation](https://hvac.readthedocs.io/en/stable/usage/auth_methods/jwt-oidc.html#oidc-authorization-url-request) there is an oddity in the example.

```python
if auth_url == '':
    return None
```

If you copy and paste this example as-is, you will see this error:

`SyntaxError: 'return' outside function`

**Comment by briantist** [comment]
Hi @Woovie , thank you for reporting this. As it happens a fix was just merged! See:
- #1010
