### ISSUE TITLE
kv2.patch() function doesn't work as expected

### ISSUE THREAD

**Issue by aakashgaur01** [hvac/hvac#793]
For a nested dictionary, kv2.patch(): should be able to update the key inside a nested dictionary but it doesnt do that; rather overwrites the whole key. Whereas if we use PATCH method for VAULT API, it works as expected. 
So in hvac also, if we can make a patch call, it would resolve the issue

**Comment by briantist** [comment]
Hi @aakashgaur01 & @vshulgin , support for nested keys is something I never realized before with the server-side patching support. I actually think this is best added to https://github.com/hvac/hvac/issues/925 and we can track the issue there . With that in mind, I'll close this issue out for now, if you think they should remain separate, please let me know and we'll consider reopening.

**Comment by briantist** [comment]
Closed in favor of #925
