### ISSUE TITLE
Cert Login: Deprecation warning but no documentation for the new way

### ISSUE THREAD

**Issue by Mordecaine** [hvac/hvac#795]
Hello,

I wanted to use the authentication method tls to authenticate at the vault. Therefor I used the way as is written in the [documentation](https://hvac.readthedocs.io/en/stable/usage/auth_methods/index.html#authenticate-to-different-auth-backends) (works really nice):
````python
# TLS
client = Client(cert=('path/to/cert.pem', 'path/to/key.pem'))
client.auth_tls()
````

If I use this way, I get the following warning:
````
Call to deprecated function 'auth_tls'. This method will be removed in version '0.13.0' Please use the 'login' method on the 'hvac.api.auth_methods.cert' class moving forward.
````

I couldn't find a different way in the documentation, and I was not able to use the hint ``Please use the 'login' method on the 'hvac.api.auth_methods.cert' class moving forward``.

Is there anyone who can help me?

Cheers,
Morde

**Comment by briantist** [comment]
The docs seem to be missing, but the implementation is there; there are some items in this library like that so it's often better to look at the source reference instead:
- https://hvac.readthedocs.io/en/stable/source/hvac_api_auth_methods.html#hvac.api.auth_methods.Cert.login

So from an instantiated Client in the variable `client`:

```python
client.auth.cert.login(...)
```

**Comment by Mordecaine** [comment]
Hello @briantist,

thank you for your help.
I changed my code now as followed.

Old Code:
````python
        certificate_path = configuration.get("certificate_path")
        private_key_path = configuration.get("private_key_path")

        connection = hvac.Client(cert=(certificate_path, private_key_path), url=configuration["url"])
        connection.auth_tls()
````

New Code:
````python
        certificate_path = configuration.get("certificate_path")
        private_key_path = configuration.get("private_key_path")

        connection = hvac.Client(url=configuration["url"])
        connection.auth.cert.login(cert_pem=certificate_path, key_pem=private_key_path
````
That works really nice.

Cheers, Morde

**Comment by Tylerlhess** [comment]
Coming back to this code I am pretty sure that I fixed it so that calling 

```
        connection = hvac.Client(cert=(certificate_path, private_key_path), url=configuration["url"])
        connection.auth.cert.login()
```

should work. 

    I say should as I think that this issue stemmed from the library not dropping all the way to the source adaptor (_adaptor). This would only add the cert to the adapter during the instantiation but not to any further instantiated adapters. This would make it so that unless the certs were used immediately with the auth_tls it would fail as soon as a new request object was built. 
    This was ultimately the fix for the issue I was having personally but, by the time I figured that out the whole cert section had been written to where I could use the certs in the login call and a few bugs had been reported on it.
