### ISSUE TITLE
Documentation outdated.

### ISSUE THREAD

**Issue by ygbourhis** [hvac/hvac#802]
The documentation here says to use the `auth_kubernetes` method : https://hvac.readthedocs.io/en/stable/usage/auth_methods/kubernetes.html
But it is deprecated and gives a deprecation warning : 
```
DeprecationWarning: Call to deprecated function 'auth_kubernetes'. This method will be removed in version '1.0.0' Please use the 'login' method on the 'hvac.api.auth_methods.kubernetes' class moving forward.
```
The documentation should show the new undeprecated method.

**Comment by ygbourhis** [comment]
I also can't find any documentation on how to use `hvac.api.auth_methods.kubernetes` properly.
Only `auth_kubernetes` works like a charm (but with a deprecation warning).
Can the warning be more helpful (with a code sample) before the deprecated code gets removed ?

Thanks in advance.

**Comment by theo-ardouin** [comment]
It looks like it's working this way:
```python
from hvac import Client, exceptions
from hvac.api.auth_methods import Kubernetes

client = Client(url=url, verify=certificate_path)
Kubernetes(client.adapter).login(role=role, jwt=jwt)
```

Cheers.

**Comment by ygbourhis** [comment]
> It looks like it's working this way:
> 
> ```python
> from hvac import Client
> from hvac.api.auth_methods import Kubernetes
> 
> client = Client(url=url, verify=certificate_path)
> Kubernetes(client.adapter).login(role=role, jwt=jwt)
> ```
> 
> Cheers.

It works.

The documentation should clearly be updated.
Thanks

**Comment by colin-pm** [comment]
Closing this issue now that #837 is merged.
