### ISSUE TITLE
Add support for custom metadata in kv2 engine

### ISSUE THREAD

**Issue by dereckson** [hvac/hvac#804]
Vault 1.9 introduced to kv2 secret engine support for custom metadata.

In addition to engine metadata like delete_version_after, max_versions, cas_required, we can add a **custom_metadata** field.

The custom_metadata field is a key/value dictionary.

Reference:
  * https://www.vaultproject.io/docs/release-notes/1.9.0
  * https://www.vaultproject.io/docs/commands/kv/metadata
  * https://github.com/hashicorp/vault-plugin-secrets-kv/pull/48

**Comment by eytanhanig** [comment]
Any updates on when this will be addressed? There's an open PR that is still waiting for a review.
