### ISSUE TITLE
KV2 path has a hard-coded /data between mount point and path

### ISSUE THREAD

**Issue by a-romm** [hvac/hvac#806]
```
api_path = utils.format_url(
            "/v1/{mount_point}/data/{path}", mount_point=mount_point, path=path
        )
```
While you can actually have a {mount_point}/{path} setup.

**Comment by LuckySB** [comment]
../data/.. is attribute only kv2 path

{mount_point}/{path} - without data is only in kv1 secrets

**Comment by Tylerlhess** [comment]
Yes this is done at the Vault level and not the hvac level. hvac is just helping you when you are using kv2 and since it is hard coded in vault to access the kv2 secrets data they have added it here also.

**Comment by a-romm** [comment]
Thank you!
Seems like, yes, it's KV2-specific.
