### ISSUE TITLE
hvac.exception.Forbidden error using hvac.secrets.kv.v2 API.

### ISSUE THREAD

**Issue by bdastur** [hvac/hvac#808]
Hi Folks,
I am trying to use the HVAC client library to interface with vault. I am successfully able to authenticate and list and read secrets using vault command line, however it fails when using hvac library. I am able to list secrets with V1 version, by adding additional `/metadata` in the path, but V2 does not work at all.

**1. Using command line:**
`> vault kv get -format=json -version=1 secret-store/s0004/static/test
{
  "request_id": "06xxc-ee04-9075-5d0e-a92fxx3f3",
:
}
`
**2. Using the hvac client.**
`vclient = hvac.Client(url="https://vault.services.xyz")
  vclient.auth.ldap.login(username="user1", password="xyz")
 > vclient.secrets.kv.v2.read_secret_version("secret-store/s0004/static/test", mount_point="")
   raise exceptions.Forbidden(message, errors=errors, method=method, url=url)
hvac.exceptions.Forbidden: 1 error occurred:
	* permission denied

, on get https://vault.services.xyz/v1/data/secret-store/s0004/static/test
`

**Note**, I am able to use the v1 version to list secrets:
`vclient.secrets.kv.v1.list_secrets(path="secret-store/s0004/metadata/static", mount_point="")`
Strangely, it only works if I insert the /metadata in the path.

**Comment by bdastur** [comment]
I think this issue can be closed.
I was able to figure out why the v2 version of API was not working. It started working after I changed my API call to pass `mount_point=secret-store/s0004` and `path=static`

eg:
`>>> vclient.secrets.kv.v2.list_secrets(path="static", mount_point="secret-store/s0004/")
{'request_id': '32f19d89-85eb-f405-2fc7-fdf598bf0c01', 'lease_id': '', 'renewable': False,....`

**Comment by colin-pm** [comment]
Yes, you must specify the mount point if the secrets engine is mounted to a path other than the default ("secret" for the KV engines).

Closing out this issue.
