### ISSUE TITLE
kv. read_secret_version has a non-customizable path

### ISSUE THREAD

**Issue by Renthal** [hvac/hvac#834]
The method `client.secrets.kv.v2.read_secret_version` has an hard-coded path formatted like this:

```
api_path = utils.format_url(
            "/v1/{mount_point}/data/{path}", mount_point=mount_point, path=path
        )
```

the `/data/` part is an issue for us as we would need to have `/vaults/` instead. 
As a side note, the method name has `v2` in it but in the path there is v1 hard-coded which is misleading. Could we just get to provide a custom string instead of hardcoded values?

**Comment by colin-pm** [comment]
> the `/data/` part is an issue for us as we would need to have `/vaults/` instead.  Could we just get to provide a custom string instead of hardcoded values?

Not sure how this is possible since "data" is hardcoded in the [Vault API](https://www.vaultproject.io/api-docs/secret/kv/kv-v2#read-secret-version) as well...

Is `/vaults/` your secrets engine mount point or part of your path?

> As a side note, the method name has `v2` in it but in the path there is v1 hard-coded which is misleading.

The Vault KV v2 engine still uses `v1` in the Vault API URL. This isn't something HVAC has any control over.

> Could we just get to provide a custom string instead of hardcoded values?

That is pretty easy to do on your own with Requests or some other HTTP library. :smiley: 

The main objective of this library is to abstract the Vault API away from the implementer.

**Comment by Renthal** [comment]
I am not an expert myself, I just know that I have a path that looks like this `"{hostname}/v1/{vault_mount_point}/vaults/{vault_key_path}"` and before (we moved to a 1pass integration) I could use the hvac library as:

```
client = hvac.Client(url=vault_address, token=vault_token)
    json_response = client.secrets.kv.read_secret_version(
        path=vault_key_path,
        mount_point=vault_mount_point,
    )
    return json_response['data']['data']
```
but because of the hardcoded /data/ this won't work (to my understanding at least). 

I am very well aware I can use Requests but I would imagine that instead of the tinkering I had to do to have the code below together (which works) I would rather use a HVAC function which is supported and maintained. Since all it changes is an hardcoded string in a path (from my point of view but i might be wrong) it seemed to be reasonable approach. 
 
```    
_va = urlparse(vault_address)  # strip the port at the end of the vault address (if provided)
hostname = _va._replace(netloc=_va.hostname).geturl()
headers = {"X-Vault-Token": vault_token}
url = f"{hostname}/v1/{vault_mount_point}/vaults/{vault_key_path}"
req = request.Request(url=url, headers=headers)
with request.urlopen(req) as response:
    json_response = json.loads(response.read())
    return json_response['data']
```

**Comment by colin-pm** [comment]
I'm not familiar with the 1pass integration, is that a modification of the open source version of Vault? Unless you're running a custom patched version of Vault, the "data" field in the path is necessary based on Vault's API spec.  If you aren't using a patched version of Vault, I'd be curious if you could find a link to the Vault docs that shows this API path. I might also be of more help if you would share what your vault_key_path and vault_mount_point are in the examples you provided.

**Comment by Renthal** [comment]
I am not sure about those part myself either to be honest. Apparently we're doing a read not a kv get... which might be causing confusion. In any case, I am closing this since apparently this might be some custom issue (even tho adding a parameter to customize that part of the url would be useful IMO)
