### ISSUE TITLE
secret mount does not exist in Vault normal mode, hence error with hvac python 

### ISSUE THREAD

**Issue by muhammad-rafi** [hvac/hvac#855]
I installed the vault in normal mode and I was trying to use python script like this 
```
# Read the device credentials from the path 'dev-creds/nxos-creds' using kv version 2 
response = client.secrets.kv.v2.read_secret_version(path='dev-creds')
print(response)
```
Error: 
`hvac.exceptions.InvalidPath: no handler for route 'secret/data/dev-creds', on get https://localhost:8200/v1/secret/data/dev-creds`

```
# Create new secret
write_response = client.secrets.kv.v2.create_or_update_secret(
                               path='dev-creds',
                               secret=dict(username='demouser', password='demopassword'),
                               )
```

`hvac.exceptions.InvalidPath: no handler for route 'secret/data/dev-creds', on get https://localhost:8200/v1/secret/data/dev-creds`

but I was getting the error same error every time no matter what I changed, I then found out the you use default mount point of 'secret' after some investigation, I wonder it may work straight away for Dev Mode but in Normal mode, 'secret' mount point is not available by default. Therefore, do you have any plans to add this in the documentation to make it clear ? 

All the examples I have seen in the documentation using the 'path' parameter only but not mentioning the mount point attribute when you install a Vault in normal mode. 

I really had to go through tough time to understand this whole thing as I was new to Vault. 

Please do also let me know if I am missing any information here or did not look at the documentation properly ?

**Comment by colin-pm** [comment]
Hi @muhammad-rafi 

The mount point is where the secrets engine is mounted on your Vault endpoint. If you go to the Vault docs, you can see the following from https://www.vaultproject.io/api-docs/secret/kv/kv-v1 and https://www.vaultproject.io/api-docs/secret/kv/kv-v2

>  This documentation assumes the kv secrets engine is enabled at the /secret path in Vault. Since it is possible to enable secrets engines at any location, please update your API calls accordingly.

HVAC was designed to use the default mount points provided by Vault to align with the Vault docs. In the case where the implementer wants to use their own custom mount points, we provide the optional mount_point parameter.

The path parameter provided by HVAC is identical to the path parameter described in the Vault docs linked above.

If I were to guess the root cause of your issue, based on the error message alone, have you created a V2 secrets engine on your Vault instance? The endpoint looks correct for the default V2 secrets engine, which leads me to believe something is not correct on your instance.

**Comment by muhammad-rafi** [comment]
Hi @colin-pm , yeah I had to manually create the secret/ mount point before I could run the above script but by default if you install the Vault in Normal Mode, there is no default mount point called secret/ and it is only available in Dev Mode, this is why I was struggling in the beginning when I started with the Vault. 

I did read about the mount point as well, and thats why I give it a go and create the secret/ mount point in my Vault Normal mode installation and then it starts working without passing the mount point parameter. But obviously for custom mount point, I am passing the mount_point parameter.

**Comment by colin-pm** [comment]
Ah, I found a page explaining Dev Server Mode and found this:

>The properties of the dev server (some can be overridden with command line flags or by specifying a configuration file):
>...
> *  Key Value store mounted - A v2 KV secret engine is mounted at secret/. Please be aware that there are differences with v1 KV. If you want to use v1, use this flag -dev-kv-v1.

https://www.vaultproject.io/docs/concepts/dev-server

Yes, if you create a production or normal instance of Vault, you will need to create your V2 secret engine.  This is how the normal workflow goes for any secrets engine when you run a normal Vault instance. In fact, you can use the HVAC API to configure a V2 secrets engine, follow the example in the link below.

https://hvac.readthedocs.io/en/stable/usage/secrets_engines/kv_v2.html#configuration

**Comment by muhammad-rafi** [comment]
Thanks for this, but I tried to create new kv2 secret engine following your link but it throws me this error, however if I tried to edit other secret engine they worked fine but they were already created, I only edit the max version value. 

```
$ python vault_secrets.py 
Traceback (most recent call last):
  File "/Users/murafi/my-github-projects/vault-devnet/vault-python-scripts/vault_secrets.py", line 107, in <module>
    secret_engine = client.secrets.kv.v2.configure(max_versions=10, mount_point='test-creds',)
  File "/Users/murafi/virtual-environments/test_evn/lib/python3.9/site-packages/hvac/api/secrets_engines/kv_v2.py", line 50, in configure
    return self._adapter.post(
  File "/Users/murafi/virtual-environments/test_evn/lib/python3.9/site-packages/hvac/adapters.py", line 126, in post
    return self.request("post", url, **kwargs)
  File "/Users/murafi/virtual-environments/test_evn/lib/python3.9/site-packages/hvac/adapters.py", line 364, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/Users/murafi/virtual-environments/test_evn/lib/python3.9/site-packages/hvac/adapters.py", line 330, in request
    utils.raise_for_error(
  File "/Users/murafi/virtual-environments/test_evn/lib/python3.9/site-packages/hvac/utils.py", line 43, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors, method=method, url=url)
hvac.exceptions.InvalidPath: no handler for route 'test-creds/config', on post https://localhost:8200/v1/test-creds/config
```

Here is the code 

```
secret_engine_config = client.secrets.kv.v2.configure(max_versions=10, mount_point='test-creds',)
print(secret_engine_config)
```

**Comment by colin-pm** [comment]
@muhammad-rafi Based on the InvalidPath exception, I think your mount point is incorrect.

**Comment by muhammad-rafi** [comment]
I see you line above `you can use the HVAC API to configure a V2 secrets engine, follow the example in the link below.` so I thought I can create new mount_point with configure method, do you know any method which we can use to enable secret engine along with the new mount_point ?

**Comment by muhammad-rafi** [comment]
thanks @colin-pm for the help, looks all good now, I am closing the issue.
