### ISSUE TITLE
Vault Eventual Consistency and 412 status code

### ISSUE THREAD

**Issue by jshively37** [hvac/hvac#882]
I have a customer who sees intermittent behavior using the HVAC library and HCP Vault. This might be related to performance standby and eventual consistency. For example, HCP directs the request to a standby node, the standby node forwards the request to the leader, the leader does its action, and then the leader syncs changes to the standby nodes. If the data is requested from the standby node during this time, it will return a 412 status code.

Can HVAC retry when it receives a 412 status code?

**Comment by briantist** [comment]
Hi @jshively37 we're discussing options for adding more direct support for retries in `hvac` , but in the  meantime you can achieve this today by creating the `requests.Session` yourself, and using the `urllib3.Retry` class.

On the `hvac` side, you can set the session when you create the `Client`, by setting `session`: https://hvac.readthedocs.io/en/stable/source/hvac_v1.html#hvac.v1.Client.__init__

A basic example of how to construct the session:

```python
from requests import Session
from requests.adapters import HTTPAdapter
from urillib3.util import Retry

adapter = HTTPAdapter(max_retries=Retry(
    total=3,
    backoff_factor=0.1,
    status_forcelist=[412, 500, 502, 503],
))
session = requests.Session()
session.mount("http://", adapter)
session.mount("https://", adapter)
```

There are many options for how to customize the retries: https://urllib3.readthedocs.io/en/latest/user-guide.html#retrying-requests

---

So I'd like to see us put some shortcuts for this in this library or in one of its adapters, with thoughtful defaults that are specific to Vault. I'll keep this issue open and consider it the feature request for that.

**Comment by jshively37** [comment]
Great minds think alike because my first suggestion to the customer was to use the requests library. 

Also, thank you for the code snippet because your approach is cleaner than I suggested.

**Comment by briantist** [comment]
Yeah the nice thing here is that you don't have to move everything to making requests yourself with the `requests` library, they only need to pass that session to `hvac` and then get all the hvac goodness, with retries being automatic.

**Comment by briantist** [comment]
@jshively37 oh! there's one thing that might be important and not so obvious: set `raise_on_status=False` when constructing the `Retry` class. The reason is that if you don't, `Retry` will raise its own exceptions that are different than the ones raised by `requests`, and that will cause the `hvac` Adapter not to catch the exceptions it expects so it can raise its own (or handle them). I'll update the snippet in the other comment.

**Comment by rtabcum** [comment]
@briantist any progress on this "Enhancement" or making this a Feature Request?

**Comment by briantist** [comment]
Hey @rtabcum , there's no news at the moment. I think it will make sense to finish up https://github.com/hvac/hvac/pull/898 first so we can solidify the direction of Adapters in hvac, and then revisit how we might offer retries as a more simple opt-in.

In the meantime, what I showed in [this comment](https://github.com/hvac/hvac/issues/882#issuecomment-1246855558) is a viable method for implementing retries today, with as much customization as you'd like. The code shown there can be used directly, and then the session object can be passed into the hvac client on creation like so: `client = Client(session=session)`

Are you looking for anything specific beyond retries?
