### ISSUE TITLE
Specify token ttl when using auth.aws.iam_login

### ISSUE THREAD

**Issue by mew1033** [hvac/hvac#889]
I'm currently logging into vault with the following:
```python
vault_client = hvac.Client(url=os.environ["VAULT_ADDR"])
vault_client.auth.aws.iam_login(
    access_key,
    secret_access_key,
    session_token,
    mount_point=os.environ["VAULT_MOUNT_POINT"],
)
```
Then I can do `vault_client.read(<path>)` no problem.

However, this uses the default token ttl. I'd like to specify the ttl for my token since I only need it for a short period of time. Is there a way to do that with hvac? Am I misunderstanding something?

Thanks!

**Comment by colin-pm** [comment]
Hi @mew1033 I think TTL can be set by creating a role for the AWS auth method. I do not think you can set TTL at login time. There appears to be a hole in our documentation regarding role-based authentication with AWS and I also am not super familiar with this auth method 😅 

I would refer you to using this method
https://hvac.readthedocs.io/en/v1.0.1/source/hvac_api_auth_methods.html#hvac.api.auth_methods.Aws.create_role

These docs may be more helpful
https://www.vaultproject.io/api-docs/v1.4.x/auth/aws#create-role

If you have any other questions, I would be happy to try and help!

**Comment by mew1033** [comment]
I ended up having the role I was using modified to set the default ttl. It'd be nice if we could request a specific ttl when logging in though, is there a way to set a feature request for that?

**Comment by mew1033** [comment]
@colin-pm, ah, that makes sense. Thanks for clarifying that for me. I'll make a feature request with them, but for now I think this can be closed.
Thanks again for the help!
