### ISSUE TITLE
readthedocs documentation is outdated

### ISSUE THREAD

**Issue by intgr** [hvac/hvac#892]
Hi. The 1.0.0 version was released today, but documentation at https://hvac.readthedocs.io/en/stable/changelog.html has not been updated.

Thanks for all the recent work on hvac!

**Comment by colin-pm** [comment]
Shoot, I did not realize it would not automatically update. I don't have access to the project on RTD and have reached out to @jeffwecan for access.

Once I have access I will update the docs and post an update on this issue.

Thanks again for your patience :sweat_smile:

**Comment by colin-pm** [comment]
Apologies that this task was closed automatically without me following up. v1.0.1 was just released, containing the fixes that ensures RTD will compile the docs. Updated documentation can be found below.
https://hvac.readthedocs.io/en/v1.0.1/
