### ISSUE TITLE
'Client.renew_self_token' method is lost

### ISSUE THREAD

**Issue by nixargh** [hvac/hvac#900]
https://github.com/hvac/hvac/blob/v1.0.2/hvac/v1/__init__.py#L360
was changed to work only with `/auth/token/renew` Vault endpoint and **renew_self_token** is mentioned there to be used instead. But there is no such method.

Maybe it was replaced by https://github.com/hvac/hvac/blob/v1.0.2/hvac/api/auth_methods/token.py#L348
But it means that at least docstring is wrong and should be updated.

**Comment by nixargh** [comment]
Nobody cares, I see.

**Comment by bendem** [comment]
Came here looking for this, how do people use this library for anything if they can't renew tokens? Or is the accepted practice to allow renewing tokens using `/renew` (that sounds like a bad idea)?

**Comment by bendem** [comment]
Ok, looking around, the method was deprecated in favor of `api.auth_methods.Token.renew_self` in https://github.com/hvac/hvac/commit/fdb4f9cbe9bcb2ce573d4def0a32035324c97e61, but the documentation was never updated accordingly.
