### ISSUE TITLE
Since Vault 1.9, step_down is forwarded to the active node

### ISSUE THREAD

**Issue by cellisten** [hvac/hvac#908]
The documentation states the endpoint does nothing:
https://github.com/hvac/hvac/blob/68aefde34ded8efb3fa29e4eb6c618229717fb8c/hvac/api/system_backend/leader.py#L22
However, since 1.9, the step_down is forwarded to the active node:
https://developer.hashicorp.com/vault/docs/v1.9.x/commands/operator/step-down

**Comment by briantist** [comment]
Hi @cellisten , thanks for submitting this and sorry for the delay in response.

If I'm understanding this correctly, it's purely a documentation issue on our end, and we need to update that to be accurate.

If you're interested in putting up a PR for that it'd be much appreciated but I think we'll be able to get that fixed soon either way.

**Comment by briantist** [comment]
HashiCorp's HTTP API docs also have not been updated, I've submitted a PR for that:
- https://github.com/hashicorp/vault/pull/23657
