### ISSUE TITLE
Nomad Secrets Backend

### ISSUE THREAD

**Issue by josegonzalez** [hvac/hvac#912]
Would you accept a minimal MR for a Nomad secrets backend? All I need to do is read a Nomad credential - so `generate_credential` - out for a given role, though here are other commands that could be implemented:

- `configure_lease(ttl=3600, max_ttl=86400)`: configure lease settings for the mount
- `configure(address, token)`: configure the mount
- `list_roles()`: list all roles in the mount
- `write_role(name, policies=[])`: add a role to the mount
- `delete_role(name)`: delete a role from the mount

**Comment by briantist** [comment]
Hi @josegonzalez ! I'm sorry for the delay in response. A PR would be appreciated if you're still up for it, thank you!

**Comment by josegonzalez** [comment]
No worries! I actually no longer work with Nomad so I no longer need this functionality. I'll close for now :)
