### ISSUE TITLE
client.auth.ldap.configure params doesn't match client.auth.ldap.read_configuration

### ISSUE THREAD

**Issue by ceesios** [hvac/hvac#974]
Configure is missing a couple of params;
    - anonymous_group_search
    - request_timeout
    - token_bound_cidrs
    - token_explicit_max_ttl
    - token_no_default_policy
    - token_num_uses
    - token_period
    - token_policies
    - token_type
    - use_pre111_group_cn_behavior
    - userfilter
    - username_as_alias #917

Also some parameters differ in their naming from the values returned by the vault api and read_configuration;
- user_dn = userdn
- group_dn = groupdn
- bind_dn = binddn
- bind_pass=bindpass
- user_attr = userattr
- discover_dn = discoverdn
- upn_domain = upndomain
- group_filter = groupfilter
- group_attr = groupattr

Would it be a good idea to add all missing parameters? And to add the parameters by their names as in the vault api, keeping the names with underscores for backwards compatibility?

**Comment by jlixfeld** [comment]
What amazing timing!  I just ran up against not being able to pass some LDAP parameters to HVAC that were in the API and found this.

Thanks for your work.  Looking forward to when this is merged.
