### ISSUE TITLE
Separate Vault backend mocking into new project

### ISSUE THREAD

**Issue by majuscule** [hvac/hvac#99]
`hvac` spins up a local vault instance for test integration. This would be super helpful for external projects that depend on vault. Can we move this code into a new repository? For my own usecase, something like `nosetest-hvac` would be most helpful (containing nosetest fixtures), but I'd be excited about any testing framework integration.

**Comment by otakup0pe** [comment]
I like this idea! I'm thinking of combining what hvac and [aomi](https://github.com/autodesk/aomi) do for HCV mocking. Thoughts on how to handle / package this are welcome! It will probably be a bunch of shell scripts I guess we could throw it in a new repo somewhere.

**Comment by jeffwecan** [comment]
Just as a general note, this is slightly easier to sort out now that we have a GitHub organization to through the new repository under. Perhaps some sort of `nosetest-vault` repo...?

**Comment by colin-pm** [comment]
Due to the inactivity of this issue and hvac-cli, I'm gonna close this issue in order to clean up the backlog of open issues. Any future work related to this can be opened in a new repo.

**Comment by jenstroeger** [comment]
@colin-pm other than the fixture referenced in issue https://github.com/hvac/hvac-cli/issues/2, what’s the recommendation regarding testing — stand up a local [Vault server](https://developer.hashicorp.com/vault/docs/commands/server)?

**Comment by briantist** [comment]
Hi @jenstroeger right now we don't have any plans for this. Could you elaborate on what you're looking for and what you're trying to do? 

The `hvac` project is an API client for Vault, and isn't seeking to provide a testing framework. This project also is not affiliated with HashiCorp, so general questions about how to test Vault are probably best directed to them.

But I can say that yes, Vault dev server is generally a pretty good way to test something that needs to hit Vault.

If you want to discuss more deepy _and it is specific to `hvac`_ consider opening a [Discussion](https://github.com/hvac/hvac/discussions).

**Comment by jenstroeger** [comment]
> But I can say that yes, Vault dev server is generally a pretty good way to test something that needs to hit Vault.

Thanks @briantist, glad to hear that.

Background: in a project at work I see folks testing their code by mocking HTTP calls to a Vault because they’ve not stood up a test Vault or use a (simple) mock Vault. I’m looking for a way to avoid mocking, and your comment suggests to use the Vault dev server — perfect 👍🏼
