### ISSUE TITLE
Custom certificate verification fails with requests>=2.28.0

### ISSUE THREAD

**Issue by satwell** [hvac/hvac#991]
With versions of requests starting with 2.28.0, I get a requests.exceptions.SSLError exception when trying to connect to a Vault instance that uses a custom SSL certificate.  Example code:

```
import hvac
import requests

s = requests.Session()
s.verify = "mycert.crt"
c = hvac.Client(session=s)
print(c.sys.read_health_status())
```

This works correctly with requests 2.27.1.  But with 2.28.0, I get the following stack trace:

```
Traceback (most recent call last):
  File "/home/satwell/tmp/hvac/status.py", line 7, in <module>
    print(c.sys.read_health_status())
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/hvac/api/system_backend/health.py", line 68, in read_health_status
    return self._adapter.head(
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/hvac/adapters.py", line 175, in head
    return self.request("head", url, **kwargs)
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/hvac/adapters.py", line 372, in request
    response = super().request(*args, **kwargs)
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/hvac/adapters.py", line 331, in request
    response = self.session.request(
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='vault.example.com', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

This doesn't seem like a bug in requests.  I can use the same requests.Session with `verify` set to successfully make a request to the same server.

I bisected changes to requests, and it looks like this problem starts with psf/requests@79c4a01.

**Comment by satwell** [comment]
When I run my test script under pdb, I can start to see the problem.  `hvac.adapters.JSONAdapter.request` is setting `verify=True` in the call to the session's `request` method.  Even though the session that it's using has the `verify` attribute set to an explicit path.

```
> /home/satwell/tmp/hvac/venv/lib/python3.9/site-packages/hvac/adapters.py(331)request()
    324             # Entry point for standard HTTP substitution
    325             params = _kwargs.get("params", {})
    326             if method.lower() == "list":
    327                 method = "get"
    328                 params.update({"list": "true"})
    329             _kwargs["params"] = params
    330
--> 331         response = self.session.request(
    332             method=method,
    333             url=url,
    334             headers=headers,
    335             allow_redirects=self.allow_redirects,
    336             **_kwargs
    337         )

ipdb> _kwargs
{'cert': None, 'verify': True, 'timeout': 30, 'proxies': None}
ipdb> self.session.verify
'mycert.crt'
```

psf/requests@79c4a01 fixed a bug in cert bundle resolution that caused `session.request(verify=True)` to effectively turn into `session.request(verify=None)` when the environment lookup for `REQUESTS_CA_BUNDLE` or `CURL_CA_BUNDLE` fails.  With `verify=None`, the `session.request` call falls back to using the `verify` setting in the session itself.

**Comment by briantist** [comment]
Hi @satwell , first I want to sincerely thank you for the thorough debugging and issue description, this is immensely helpful.

As I look at this I'm trying to think what the best solution is for the issue. For sure, we could improve the documentation.

I'm also wondering if it makes sense to inspect `session` and skip "default" `verify` processing in that case (only when `verify is None`). Part of me wonders if that's a slippery slope, but it I suppose it would only apply to params where we do this type of complex default processing (looking at `cert` too, which if I'm reading the code right, would also override a `cert` set on a passed in `session`).

Do you have any thoughts on how you'd like to see it addressed?

**Comment by Tylerlhess** [comment]
Having written the aforementioned code I support taking the session data if available. If I remember correctly from when I wrote this I just followed the existing code or based it off code from a similar requests implementation. If this is truly overriding the session variables it might explain why the certificates aren't sticky to the session under certain circumstances. This was a problem that I was unable to resolve in some cases and this solution might be the one I was looking for in the first place. 

I would prioritize the current session variables and don't know why I wouldn't have done such in the first place. All the requests sessions and adapters code is quite complex as it is so I know how easy it is to mix up the actual code implementation as that was what I originally set out to fix while writing this section.

**Comment by briantist** [comment]
Thanks @Tylerlhess , I appreciate the additional context.

So it sounds like you'd be in favor of this, is that correct?

> I'm also wondering if it makes sense to inspect `session` and skip "default" `verify` processing in that case (only when `verify is None`). Part of me wonders if that's a slippery slope, but it I suppose it would only apply to params where we do this type of complex default processing (looking at `cert` too, which if I'm reading the code right, would also override a `cert` set on a passed in `session`).

**Comment by satwell** [comment]
I'd consider removing the [verify setting in `hvac.adapters.Adapter._kwargs`](https://github.com/hvac/hvac/blob/3d6f98d19d0c63a73e07bc755815d8fd6ebcb83c/hvac/adapters.py#L78).  The `_kwargs` dict gets passed in as keyword args to every `session.request` call.  This is problematic, because the `verify` setting is stored in two places:  once in the session, and once in the adapter.

The adapter is already creating the session unless the user provides their own.  So it can (and already does) set `session.verify` correctly when creating the session.  The adapter should just assume that `session.verify` is set correctly when it uses it later, and not pass `verify` again to `session.request`.

In addition to simplifying the adapter code a bit, it's also a little clearer what happens if the user passes in their own `session`, or if they happen to change it after the adapter has already been created.  The contract with the user becomes: hvac will handle verification according to the `verify` arg passed to `Client`, or the user can provide their own session to `Client` and they are solely responsible for configuring the session to do what they need.

This principle could probably be extended to other similar settings like `cert` and `proxies` as well.

**Comment by briantist** [comment]
@satwell that's a good point, and I think I agree.

One issue is that this would be a breaking change.

For the condition where:
- user creates session without setting `verify` (and other parameters like `cert` and `proxies`)
- user passes their session to the client
- user relies on current `hvac` defaults for these values

It's not just theoretical, I think many cases of custom session usage do this, for example: https://hvac.readthedocs.io/en/stable/advanced_usage.html#retrying-failed-requests

And stopping setting those values cold may lead to incorrect assumptions about what is being verified or even causing breakage.

That being said, I still support what you're saying; I think we could do this over the course of a few major releases, and we could possibly use the method of inspecting `session` as an intermediate step, so I'm thinking something like this:
1. Put in a change that inspects `session` and avoids applying `hvac` defaults when those aspects of the session are already set 
2. Announce that in major version `X.0.0`, a passed in session will be used as-is without modification
3. In version `X.0.0` we drop the intermediate change, and stop messing with `session` completely

Does that sound viable to you? Also interested in your thoughts @Tylerlhess

**Comment by Tylerlhess** [comment]
I think this is actually a simple fix having looked at the code.

I should be able to get a pr in with proposed changes today. 
Should only be a line or two of code that would also not be a breaking change. 

basically if [this](https://github.com/hvac/hvac/blob/3d6f98d19d0c63a73e07bc755815d8fd6ebcb83c/hvac/adapters.py#L63) check fails (there is an existing session) we just add an else clause that sets verify to the session's verify if it is not None.  I want to say that verify is assumed and required deeper in the library and thats why it was being set there but I can't say for certain at this moment.

**Comment by Tylerlhess** [comment]
> verify is never used again directly, the _kwargs dict is used in the code

Yes, I think some of the underlying calls require those settings and that is why we have it coded that way. But once again I haven't tried testing that or removing that section to find the actual issue locations if they exist.
